### ISSUE TITLE
New item may be collapsed, but not uncollapsed

### ISSUE THREAD

**Issue by michael-e** [symphonists/subsectionmanager#10]
Clicking the "create new" button, the edit area will be uncollapsed. If you collapse it, you can't uncollapse it again. Still the new item will remain in the list, useless.

**Comment by nilshoerrmann** [comment]
Das Problem habe ich jetzt noch nicht so ganz verstanden ...

**Comment by michael-e** [comment]
- click on the "create new" button
- you'll see a header ("New item - please fill out the form below"), and the edit area for this item will automatically uncollapse
- if you click on the "New item" text, the darker edit area will collapse
- try to uncollapse the edit area by clicking again -- it uncollapses, but immediately re-collapses

**Comment by nilshoerrmann** [comment]
Ah, I see. Thanks!

**Comment by nilshoerrmann** [comment]
Fixed this issue locally and will push all relevant changes to GitHub soon.

**Comment by nilshoerrmann** [comment]
http://github.com/nilshoerrmann/subsectionmanager/commit/3eb83de5a23904d667f165209f696a07abfa79d0
