### ISSUE TITLE
Unnecessary Version code

### ISSUE THREAD

**Issue by brendo** [symphonists/subsectionmanager#100]
https://github.com/nilshoerrmann/subsectionmanager/blob/merging/fields/field.subsectionmanager.php#L469-471

**edit** woohoo #100 :D

**Comment by nilshoerrmann** [comment]
> edit woohoo #100 :D

Pass "Go" collecting 5 extra bugs :)

**Comment by nilshoerrmann** [comment]
By the way, if you like I can grant you push rights.
