### ISSUE TITLE
Styling of new items w/ preview images in drawer 

### ISSUE THREAD

**Issue by johannahoerrmann** [symphonists/subsectionmanager#105]
When creating a new item with a file attached / when attaching a file to an item and saving it, the styles for this item are somewhat off in the drawer (no class assigned to newly saved item `li`). When reloading the page, everything looks fine again (and `class="preview"` is assigned).

![Style error - with preview image](http://projekte.nilshoerrmann.de/screenshots/sym_ssm-styleerrorpreviewimage.png)
![Matching code](http://projekte.nilshoerrmann.de/screenshots/sym_ssm-styleerrorpreviewimagecode.png)

I thought this only occurs when "show preview image" is selected for this field, but then I unchecked this option, reloaded the page and was confronted with another style problem. Reloading the page didn't bring any changes.

![Style error - without preview image](http://projekte.nilshoerrmann.de/screenshots/sym_ssm-styleerrordrawer.png)
![Matching code](http://projekte.nilshoerrmann.de/screenshots/sym_ssm-styleerrordrawercode.png)

**Comment by johannahoerrmann** [comment]
Not sure if this makes a difference, but this particular Subsection Manager is included in Subsection Tabs.

**Comment by nilshoerrmann** [comment]
To things seem to be missing:
1. the `preview` class in the first example,
2. the padding in the second example.
