### ISSUE TITLE
Drawer height and visibility

### ISSUE THREAD

**Issue by johannahoerrmann** [symphonists/subsectionmanager#112]
After saving an item, the drawer height does not adjust correctly. When saving, the spinning icon appears, then the drawer is closed completely, opened to the right height and then cut off a bit at the bottom. (The missing height seems to be the height of the notification message.)

![drawer height](http://projekte.nilshoerrmann.de/screenshots/sym_ssm-drawerheight.png)

(This problem occurred in the installation for Wettl. on our project server.)

**Comment by nilshoerrmann** [comment]
Title updated to reflect referenced/merged issues as well.

**Comment by nilshoerrmann** [comment]
I think I've fixed this locally in the `2.x`. Will push everything as soon as I finished cleaning up that branch (this might take a moment).
