### ISSUE TITLE
z-index of stage

### ISSUE THREAD

**Issue by johannahoerrmann** [symphonists/subsectionmanager#113]
The z-index of stage seems to be so high that it is displayed over the main backend navigation:

![stage z-index](http://projekte.nilshoerrmann.de/screenshots/sym_ssm-stagezindex.png)

(This problem occurred in the installation we run for Wettl. on our project server.)

**Comment by brendo** [comment]
For reference the z-index of Stage is 1000.

The z-index for the navigation is 3

**Comment by nilshoerrmann** [comment]
This should be fixed in the Stage repo.
