### ISSUE TITLE
SSM uses the deprecated $page /administration/

### ISSUE THREAD

**Issue by brendo** [symphonists/subsectionmanager#115]
Symphony swapped from using `/administration/` to `/backend/` for the delegate page subscription value in [October 2009](https://github.com/symphonycms/symphony-2/commit/70655c7a5b53835334b3bb2dfd0ec9452246e521) and it was unofficially deprecated then (inline comment, not the best I agree).

In the next release of Symphony, I've been looking at the current bottlenecks and at present there is some logic that checks for the instance of `/administration/` and maps it to the correct `/backend/` string. I'd like to remove this unnecessary code in the core for a little speed boost.

Looking through a large list of extensions, SSM was on of the ones that uses `/administration/` to register for the `AdminPagePreGenerate` delegate. Changing this to `/backend/` would be my recommendation :)

**Comment by nilshoerrmann** [comment]
Thanks for the report - I will adjust the delegate context as soon as I find some spare time (two weeks of intense client work lie ahead).

PS: I just added you as collaborator to this repository. So feel free to push the changes yourself.
