### ISSUE TITLE
Mouseup event re-opens "Edit" panel

### ISSUE THREAD

**Issue by nickdunn** [symphonists/subsectionmanager#12]
Steps to reproduce:
- click on an item to expand the "edit" panel
- click on the item again to collapse, but this time keep your mouse pressed until the panel closes
- let go once the panel has collapsed, and mouseup will open the panel again

**Comment by nilshoerrmann** [comment]
> click on the item again to collapse

That should not be possible. Collapsing should only work when you click outside the item or its drawer. I'll have a look into that.

**Comment by nilshoerrmann** [comment]
I cannot reproduce this issue. Nick, is this still an issue for you?

**Comment by nickdunn** [comment]
Nope, it looks like this has been resolved.
