### ISSUE TITLE
Droptext not displayed in 1.2RC2

### ISSUE THREAD

**Issue by animaux** [symphonists/subsectionmanager#123]
n/t

**Comment by nilshoerrmann** [comment]
What's happening instead?

**Comment by animaux** [comment]
Only the black standard label is displayed, the defined droptext is simply missing.

**Comment by nilshoerrmann** [comment]
I cannot reproduce that using either `1.2` or `2.0`.

**Comment by animaux** [comment]
Maybe I didn’t understand the whole thing about droptext at first … I realise now, that it is the text, that is displayed when dragging items into text-areas, right? I’m not using this feature at all, but I do use the droptext to get that second, grey line of description text in the backend when using subsections. And that’s where the string defined as droptext is not displayed anymore.

**Comment by animaux** [comment]
I dare to reopen the issue thus … :)

**Comment by nilshoerrmann** [comment]
Kannst Du mir einen erläuternden Screenshot schicken? Ich komme nicht mehr mit.

**Comment by ahwayakchih** [comment]
Droptext is the text that will be "dropped" ("pasted") into textarea.
Caption is the one that is displayed on the item and while item is being dragged.
