### ISSUE TITLE
`__parseSubsectionFields` plays havoc with `$mode`

### ISSUE THREAD

**Issue by brendo** [symphonists/subsectionmanager#132]
I found this out while investigating some obscure bug, but regardless, this can affect any field that utilizes the `$mode` and the second part affects the whole site's speed.

The easiest way for you to reproduce is to create a Textarea and don't set a formatter. The value of the textarea will never be included in a datasource now because SSM will parse the included elements to be `test`: `handle-of-ds`. The textarea field strictly detects the `$mode` to be `null`, `formatted` or `unformatted`. It will get passed `handle-of-ds`, so it won't be output.

Something that is probably of more concern is that this function runs on every Datasource, regardless of if a SSM is involved or not, which creates an overhead for every datasource of the entire site. From I can tell, this means every included element of every datasource incurs a 2-3 query penalty.

**Comment by ahwayakchih** [comment]
Can You check https://github.com/ahwayakchih/subsectionmanager/commit/326c3b48bcf5115a575257f0c16ba3ea3c681366 and see if Textarea problem is fixed? I am not sure how it will work if such textarea is field of subsection (i still have to test that), but it does work with textarea in root section.

> Something that is probably of more concern is that this function runs on every Datasource, regardless of if a SSM is involved or not, which creates an overhead for every datasource of the entire site.

You are right. I think SubsectionManager should parse fields and cache data when Data Source is saved (i think there is delegate for that, right?), and then just load cache when Data Source calls `DataSourceEntriesBuilt`.

**Comment by ahwayakchih** [comment]
Just tested it with Data Source selecting textarea from subsection. Works OK :).

**Comment by brendo** [comment]
Yep I can confirm the original bug has been fixed. Should we create another issue for the latter?

**Comment by ahwayakchih** [comment]
Yes, please :). Though it probably is not about 2-3 queries penalty anymore. Since it does not try to handle "regular" fields that are not part of subsection anymore, there should be not much slow down.
We just need to make SSM know which Data Source contains fields that SSM should handle, so it will not try to check all fields of every Data Source. I was thinking about parsing field data when Data Source is saved, but if any field would change after that, SSM would not know that.

**Comment by brendo** [comment]
Opened #135
