### ISSUE TITLE
`preloadSubsectionEntries` assumes `$parents` will be an array

### ISSUE THREAD

**Issue by brendo** [symphonists/subsectionmanager#133]
Resulting in:

Invalid argument supplied for foreach()

An error occurred in /Users/brendanabbott/Sites/symphony-2.local/extensions/subsectionmanager/extension.driver.php around line 337

```
332:          */
333:         public static function preloadSubsectionEntries($parents) {
334:
335:             // Get parent data
336:             $fields = array();
337:             foreach($parents as $entry) {
338:                 $data = $entry->getData();
339:                 
340:                 // Get relation id
341:                 foreach($data as $field => $settings) { 
```

I'd recommend setting the function to (array $parents = array()) or checking that $parents is actually an array before running foreach

**Comment by ahwayakchih** [comment]
Fixed in https://github.com/nilshoerrmann/subsectionmanager/commit/2497a4edc3ac48843c88e3052e73d97a3e0d6a24 - thanks!

**Comment by brendo** [comment]
Confirmed

PS: If you just type # {issue-number} (without the space between) in your commit messages, github will automatically link it to the relevant issue.

**Comment by ahwayakchih** [comment]
Cool, thanks :).
