### ISSUE TITLE
XML: Subsection Managers inside Subsection Tabs

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/subsectionmanager#136]
When adding a SSM to a SST, the XML won't return anything for the SSM field.

@ahwayakchih: Do you have an idea why this is happening. I guess it is due to the new recursion setting but I think I'm not quite up-to-date.

**Comment by nilshoerrmann** [comment]
Hm, it seems like this is not happening on all of my SSM fields. I'll investigate ...

**Comment by ahwayakchih** [comment]
I did not touch SST field, so there might be something broken.
Recursion setting should probably be described better, but i am not sure how. It sets how many times selected field (setting is changed per field) can show up in the "fields path". For example: section "Blocks" has SSM field "Parts" pointing to Blocks. If recursion of "Parts" field is set to none, XML will not contain any parts. If it is set to one, it will show only children (1st level of parts). If it is set to two, it will show grandchildren too (children of children, parts of parts, 2nd level of parts :).

**Comment by nilshoerrmann** [comment]
This is somehow strange –. I have two section with Subsection Tabs:
- The first one contains a SSM to attach documents which are all returned nicely in the XML.
- The second one contains a SSM to attach books that contains another SSM manager with authors. None of these managers are returned in the XML.

**Comment by nilshoerrmann** [comment]
This is the field storage for that problematic section:

```
Array
(
    [73] => Array
        (
            [70] => Array
                (
                    [0] => formatted
                )

            [74] => Array
                (
                    [0] => formatted
                )

            [71] => Array
                (
                    [0] => formatted
                )

            [72] => Array
                (
                    [0] => berichte/titel
                )

        )

    [75] => Array
        (
            [16] => Array
                (
                    [0] => 
                )

            [15] => Array
                (
                    [0] => 
                )

            [17] => Array
                (
                    [0] => 
                )

        )

    [63] => Array
        (
            [29] => Array
                (
                    [0] => 
                )

            [106] => Array
                (
                    [0] => 
                )

            [31] => Array
                (
                    [0] => 
                )

        )

)
```

Field `72` is my SSM inside SST. But there are no subfields stored for that field.
(`75` and `63` are SSM fields outside of SST.)

**Comment by nilshoerrmann** [comment]
Ah, sorry, my mistake: I printed the wrong `$mode` context. The subfields are stored correctly, but SSM won't generate any output for some reason.

**Comment by nilshoerrmann** [comment]
Aha! It seems like the "I don't show unsorted items" bug returned. When I sort my subsection, everything will be fine again.

**Comment by ahwayakchih** [comment]
Hmm... it might be because of changes in handling sortorder, but it should show up unsorted entries anyway. Maybe update queries did not update database properly?

**Comment by ahwayakchih** [comment]
What i mean is that "sortorder" is now natural result of storing entries in `tbl_entries_data_X`. They are stored in order selected on edit page. So they should be returned in XML, no matter what.

**Comment by nilshoerrmann** [comment]
Oh, really? How could I've missed that! You've been really busy pushing this extension forward.

So this means that these routines are no longer needed, right?
https://github.com/nilshoerrmann/subsectionmanager/blob/master/fields/field.subsectionmanager.php#L761-786

**Comment by ahwayakchih** [comment]
Yes, but only in `multiple` branch :).

**Comment by nilshoerrmann** [comment]
Right, that's the missing piece in my puzzle :D

**Comment by ahwayakchih** [comment]
https://github.com/nilshoerrmann/subsectionmanager/blob/multiple/fields/field.subsectionmanager.php#L719 :D

**Comment by nilshoerrmann** [comment]
Okay, switching to the `multiple` branch solves the issue. Thanks!

**Comment by ahwayakchih** [comment]
Great. Did the update process work OK? I did not add query to remove data from sort table yet, so it should be possible to compare if everything is sorted like it should be.

**Comment by nilshoerrmann** [comment]
I actually don't know: there were no sorted entries before (only one that I sorted to get XML output working).

**Comment by ahwayakchih** [comment]
OK, it worked here, but it is always better if more people can test it :).
Good thing that they do show up anyway, so no data was lost ;).

**Comment by nilshoerrmann** [comment]
> Good thing that they do show up anyway, so no data was lost ;).

:)
