### ISSUE TITLE
Phantom elements

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/subsectionmanager#139]
There are some strange `<i>` elements in the `label` of SSM using the latest `2.x` code. Might be related to JavaScript but I couldn't find the real reason yet.

**Comment by ahwayakchih** [comment]
I cannot see any of them here. Can you paste HTML code that contains those phantom `<i>` elements? Are you using some other extensions that may add such things, e.g., [Custom field captions](https://github.com/brendo/customfieldcaptions)?

**Comment by nilshoerrmann** [comment]
Custom captions might be the culprit – I'll check that.
