### ISSUE TITLE
Incorrectly follows link to image asset

### ISSUE THREAD

**Issue by nickdunn** [symphonists/subsectionmanager#14]
When adding an entry from a keyword search, click on that entry in the list (when it has an image) takes me to that image. This means I cannot drag and drop (upon dropping it loads the image).

To reproduce:
- select an image from the available list by clicking on it
- the image row is added to the selected list at the top
- click on the row added to the selected list

**Comment by nilshoerrmann** [comment]
I thought this was fixed. I'll have a look at it.

**Comment by nilshoerrmann** [comment]
I cannot reproduce this behaviour neither using Firefox nor Safari (both on Mac OS X). Could you please check if this is still an issue using the latest code?

**Comment by BBQbrains** [comment]
This happened to me using Chrome on Windows. When I updated my WMD Editor extenstion to fix a problem in IE8, the image linking problem in Chrome disappeared.

**Comment by nilshoerrmann** [comment]
Can you verify that this is Subsection Manager related issue and not a WMD Editor one? Do you get any JavaScript related errors in your console?
