### ISSUE TITLE
allow_nonunique

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/subsectionmanager#143]
Why don't we make it simpler and call it `allow_quantities`?

**Comment by brendo** [comment]
I think that's a good idea, double negatives are always confusing! `disable_query_caching` is a famous one, or at least how it was implemented.

**Comment by ahwayakchih** [comment]
Yes, of course. I did not know how implementations will end up, so i was avoiding word "quantity" (i was trying to make implementation allow to have items selected like: A x 2, B x 1, A x1, i.e., the same item selected multiple times, but sorted into two different positions). It ended up simpler way, so yes, "quantity" is a perfect word there now.
