### ISSUE TITLE
Recursions

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/subsectionmanager#144]
I think the new recursion settings is quite confusing. @ahwayakchih could you explain what it does exactly?

Maybe this should only be a hidden "pro" features with a general SSM setting allowing 1 level of recursion (which would enable one Subsection Manager inside another as far as I understand).

**Comment by nilshoerrmann** [comment]
What about hiding this setting for subsection that do not contain other Subsection Managers? In theses cases no recursion is needed, right?

**Comment by ahwayakchih** [comment]
I tried explaining it in another thread. It is set per field, and it decides how many times that field can be "parsed" in the selected "path of fields". So if path looks like "a/b/c/a/d" it needs recursion set to 2 to allow selecting content of "d".

I think we can hide it if selected subsection does not contain any SSM fields, but then developers will have to re-edit field settings if they later add SSM field to subsection. There will be no way to setup recursion before adding SSM fields to subsection. I often use SSM within SSM, so for me it is a common setup, but if others rarely use that we can hide it :).

**Comment by nilshoerrmann** [comment]
That's a good point. I'm just trying to simplify things - and I think the term "recursion" is problematic. Maybe something like "nested subsections" is easier to understand for the normal users.

**Comment by ahwayakchih** [comment]
Yes, i think it could use more understandable label. "How many times this field can be nested in Data Source" could be better, but it is too long :). Maybe best would be some short label and additional help text below.

**Comment by nilshoerrmann** [comment]
I will have a look at the labeling.

**Comment by ahwayakchih** [comment]
Thanks.
