### ISSUE TITLE
Quantities

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/subsectionmanager#146]
Something is wrong with the quantities: even if they are disabled, they are displayed for newly created items. 

Furthermore it's quite confusing that the quantifiers are added to the field `label` first and then moved using JavaScript. Why aren't they just added to the templates in `/lib/class.subsectionmanager.php`?

**Comment by ahwayakchih** [comment]
> Something is wrong with the quantities: even if they are disabled, they are displayed for newly created items.

I will fix that.

> Why aren't they just added to the templates in /lib/class.subsectionmanager.php?

Like i wrote before: i wanted to do as little changes as possible and did not change class.subsectionmanager.php, so it would be safer to marge it. Now we can clean that up by moving HTML generation from `field.subsectionmanager.php` to `class.subsectionmanager.php`.

One step at a time :).

**Comment by nilshoerrmann** [comment]
> One step at a time :).

You're certainly right about that. But it's quite complicated to track errors at the moment because things are spread across multiple places. But we'll manage that :)

**Comment by ahwayakchih** [comment]
> But we'll manage that :)

Yep :).

**Comment by ahwayakchih** [comment]
As of https://github.com/nilshoerrmann/subsectionmanager/commit/5173987bbbe9f74f7d6f3b89fc23d63a41d36274 it should be ok.
