### ISSUE TITLE
Filtering still doesn't work

### ISSUE THREAD

**Issue by benesch** [symphonists/subsectionmanager#147]
I'm getting the exact same error described in [Issue 53](https://github.com/nilshoerrmann/subsectionmanager/issues/53) when I try to filter by a Subsection Manager field. As noted by the last comment there, the code Nils provided works perfectly but appears never to have been committed.

:(

**Comment by ahwayakchih** [comment]
It is already commited in 1.x branch (2.x branch also has that code, just with additional option to filter by quantity).

https://github.com/nilshoerrmann/subsectionmanager/blob/1.x/fields/field.subsectionmanager.php#L680
