### ISSUE TITLE
It is not obvious that items are draggable

### ISSUE THREAD

**Issue by nickdunn** [symphonists/subsectionmanager#15]
This was brought up on the forum. I would like to suggest that the default cursor is the "drag" cursor, making it plainly obvious that items can be re-orderable (which is a killer feature!). Perhaps there should be an "edit" button beside the "X" button?

To me, it is more probably that a user would want to re-order than edit, so the more frequent action should have precedence.

(But that's just me.)

**Comment by nilshoerrmann** [comment]
Changing the cursor is a good idea but I'm not sure about the "edit" button. The Manager should be able to distinguish between clicking and dragging (which is the same for sorting and drag and drop). 

Why do you think we need an "edit" button?

**Comment by nickdunn** [comment]
Hmm. If the cursor is changed to the draggable/hand cursor, then there is no indication that the rows are _clickable_. Currently there are two cursor styles: the "pointer" style indicating that the row is clickable, and a text/caret cursor when you mouse over an `<em>` in a row.

By removing the click functionality entirely you would adhere more to Symphony's own drag and drop for entry tables (e.g. the Pages/Sections lists), perhaps both in style and behaviour.

**Comment by nilshoerrmann** [comment]
I'll think about this.

Technically there is a radius setting: the reordering process will start if the user holds down the mouse button and moves outside a radius of 3 pixels. If the cursor is still inside the radius the click event is fired.

**Comment by nilshoerrmann** [comment]
The selection list will now use `cursor: move` for draggable item list. Only the preview images and the caption will show a `pointer`.
