### ISSUE TITLE
Visual JS and CSS broken

### ISSUE THREAD

**Issue by designermonkey** [symphonists/subsectionmanager#150]
I'm seeing some strange behaviour with the styling of SSM today.
1. I create a new entry, it opens the entry correctly.
2. When I save the entry, the entry rolls up, then flicks out of position vertically (up) and rolls back down.
3. Closing the newly created entry leaves the bottom of SSM laying slightly over the top of the new entry row.
4. Opening the entry and resaving changes breaks the entry view and the spinner is left pinning.

If you need pictures I can provide them... Just don't know how yet on Github ;o)

**Comment by ahwayakchih** [comment]
Can it be somehow related to #112?

**Comment by designermonkey** [comment]
Yes it is the same issue. I didn't know it was called the drawer...
