### ISSUE TITLE
"Can only flip STRING and INTEGER values"

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/subsectionmanager#151]
After updating to Symphony 2.2.2beta2 and the latest SSM version (`2.x`), I'm locked out of the backend with this message:

```
array_flip() [function.array-flip]: Can only flip STRING and INTEGER values!
/Users/nilshoerrmann/Sites/Webseiten/nilshoerrmann.de/extensions/subsectionmanager/lib/class.subsectionmanager.php line 149

144             }
145             else if(!is_array($items['relation_id'])) {
146                 $items = array('relation_id' => array($items['relation_id']), 'quantity' => array($items['quantity']));
147             }
148             print_r(    $items['relation_id']);         
149             $sortorder = array_flip($items['relation_id']);
150         }
151
152         // Filter entries and add select options
153         $entry_data = array();
```

Investigating the reasons.

**Comment by nilshoerrmann** [comment]
This issue only happens on section index pages and seems not to affect edit pages.

**Comment by ahwayakchih** [comment]
Can you `var_dump($items)`?
It looks like `$items` was array, but `$items['relation_id']` was not set. Code should make `$items['relation_id'] = $items`, but it looks like something went wrong.

I have latest integration branch of Symphony and latest version of SSM 2.x here, and problem you described does not happen. It probably depends on specific section setup.

**Comment by nilshoerrmann** [comment]
That's how the array looks like (right before it should be flipped):

```
Array
(
    [relation_id] => Array
        (
            [0] => 
        )

    [quantity] => Array
        (
            [0] => 
        )

)
```

**Comment by ahwayakchih** [comment]
Thanks. In fiture use `var_dump` instead of `print_r`, because it clearly shows `false` and `null` values too.

I will fix (well... workaround, because i am not sure why empty values are there in the first place) this later today.

**Comment by nilshoerrmann** [comment]
Right, here we go:

```
array(2) {
  ["relation_id"]=>
  array(1) {
    [0]=>
    NULL
  }
  ["quantity"]=>
  array(1) {
    [0]=>
    NULL
  }
}
```

**Comment by ahwayakchih** [comment]
I got mail notification about your comment, that included more data in array, and that was a lot more interesting because there were `NULL` values there only for the first item. Rest of items in array were not empty. That is really strange because empty values should not be saved to database. Could you check if database table for this field contains "empty" values (`0`, empty string, `false`, etc...)?

**Comment by ahwayakchih** [comment]
[1a13169](https://github.com/nilshoerrmann/subsectionmanager/commit/1a13169499f58c77726ebd3b890354cfe439397c) should fix the problem (well... symptoms of problem, because empty values should not be there :).
