### ISSUE TITLE
Styling issues in IE8 & IE9 (possible IE7?)

### ISSUE THREAD

**Issue by kanduvisla** [symphonists/subsectionmanager#152]
In IE8, the following happens with the last master-branch:

The form is positioned too high:

![styling issue 1](http://i.imgur.com/htPh9.png)

When creating an entry, the preview image is shown too small. Clicking again on 'Save changes' makes the image show in the correct height, but you would expect this to happen instantly:

![styling issue 2](http://i.imgur.com/plNQA.png)

**Comment by nilshoerrmann** [comment]
Is this a new SSM install or an updated version?

**Comment by kanduvisla** [comment]
It is version 1.2, the current master

**Comment by nilshoerrmann** [comment]
No, I mean did you update from an earlier version or is this a new install of the extension?

**Comment by kanduvisla** [comment]
a new install

**Comment by kanduvisla** [comment]
...or is it? Now you're making me doubt. It is a website we worked on for a long while. Why should it matter if it's a new install or not?

**Comment by nilshoerrmann** [comment]
It might be related to either caching or Stage being out of date.

**Comment by nilshoerrmann** [comment]
Can you check, if you've go this code in your version?

https://github.com/nilshoerrmann/subsectionmanager/commit/db760f5904d802d8a6141be775d44d1e28a9ceaf

(This is a similar issue in Firefox: https://github.com/nilshoerrmann/subsectionmanager/issues/88#issuecomment-1025684)

**Comment by kanduvisla** [comment]
I've got this code in my version

**Comment by animaux** [comment]
I had a similar issue when using Documenter. There seems to be an incompatibility with Documenter (Johannas Fork) and Subsection Manager. When I deactivate the former, all is well.

**Comment by s-e** [comment]
I'm also still having stylesheet issues with IE8 and various extensions being displayed through subsections.

Issues:
https://github.com/klaftertief/imagecropper
Jcrop crop area box is a grey matte and not transparent. Loading animation is permanently overlaid on image preview

https://github.com/kanduvisla/symphony-ckeditor
Format Icons are grey mattes.

**Comment by nilshoerrmann** [comment]
Moved to #112.
