### ISSUE TITLE
Creating a new entry should cause the opened entry to collapse

### ISSUE THREAD

**Issue by kanduvisla** [symphonists/subsectionmanager#153]
When creating an entry, and another, and another, and another, the already opened entry should collapse. (I believe this was default behaviour previously). Otherwise, you get something like this:

![to much entries](http://i.imgur.com/5O7Y2.png)

**Comment by ahwayakchih** [comment]
You're right. It would be better if other entries were automatically collapsed when user clicks "create new".

But there is one corner case when it could be annoying: when you create new entry and want to copy parts of other entry.
That is why option to have more than one entry "opened" should be kept.

**Comment by nilshoerrmann** [comment]
This is intended behaviour – otherwise comparing entries will not be possible. You have to close the editors manually or click outside the manager to collapse all.

(But it's correct, that older version behaved differently.)

**Comment by kanduvisla** [comment]
But clickling outside the manager doesn't collapse all. Still a bug?
