### ISSUE TITLE
Implement `prepareImportValue` function for XML Importer support

### ISSUE THREAD

**Issue by brendo** [symphonists/subsectionmanager#154]
Just was doing a quick look around open pull requests on @rowan-lewis's extensions and found [this one](https://github.com/rowan-lewis/xmlimporter/pull/2)

Should be simple to integrate.

**Comment by ahwayakchih** [comment]
What `prepareImportValue` should do? I checked [XMLImporter](https://github.com/rowan-lewis/xmlimporter/blob/master/lib/class.xmlimporter.php#L213) but would have to read more of its code to know for sure.

Change proposed by **designermonkey** was something about not allowing multiple selection, that is why i am confused, what should be done. SubsectionManager can have multiple values or not, depending in its settings.
