### ISSUE TITLE
Warning: Call-time pass-by-reference has been deprecated

### ISSUE THREAD

**Issue by patrickyan** [symphonists/subsectionmanager#156]
This error appears on the top of the backend (But otherwise the extension seems to work).

Symphony 2.2.2

Warning: Call-time pass-by-reference has been deprecated in /home/trimedicine/trim-edicine.com/extensions/subsectionmanager/fields/field.subsectionmanager.php on line 474

**Comment by ahwayakchih** [comment]
Thanks for report. Should be fixed in 1.x branch now.

**Comment by patrickyan** [comment]
Perfect!
