### ISSUE TITLE
Call to a member function fetch() on non-object

### ISSUE THREAD

**Issue by davidhund** [symphonists/subsectionmanager#157]
I have added a `reflectionfield` (simple _name last-name_) to a section and upon saving an entry I get this error re: line 725 of field.subsectionmanager.php. The error goes away and I am able to save the entry when I remove the refrlection field...

My Section (Worker) contains one SSM (for Images) and a SSM Tabs linking to a _Worker-Translations_ Section for multi-lang content.

It's a mystery to me how a reflectionfield would trigger this error for SSM.

**Comment by ahwayakchih** [comment]
Which version of SubsectionManager are you using? There was some fatal error fixed lately in 2.x branch, so you might try to update it, if you're using 2.x version.

**Comment by davidhund** [comment]
To be honest: I'm a bit confused by all the branches/versions of SSM. Anyway, when I `cd` in my `subsectionmanager` submodule directory and do a `git branch -v` I get this: `* master 994b4f8 Subsection Manager 1.2` indicating I am using the latest commit of June 16 in the `1.2` `master` branch.

What are the differences between the `1.x` `2.x` and `development` branches, compared to 'my' `master`?

**Comment by ahwayakchih** [comment]
I am not sure about `development` branch. `1.x` is work in progress for current `master` branch.
`2.x` is a next version of SSM which contains a lot of changes and a new field type (Subsection Tabs). Upgrading process from `1.x` is not finished yet, so you might want to wait for "official" release (when `master` will contain code from `2.x` branch).

I am not sure what error you are getting, so i am guessing here. Try to change lines, so you have something like this:

```
        // Fetch field data
        if (!class_exists('EntryManager')) {
            require_once(TOOLKIT . '/class.entrymanager.php');
        }
        $entryManager = new EntryManager(Symphony::Engine());
        $entryManager->setFetchSortingField($this->get('id'));
```

**Comment by davidhund** [comment]
Thank you for your reply. The branches are somewhat clear now. Re: the code: in what file, at what method/location do I need to change this?

**Comment by nilshoerrmann** [comment]
The development branch is there for legacy reasons.

**Comment by ahwayakchih** [comment]
> in what file, at what method/location do I need to change this?

The one that was mentioned in error: `field.subsectionmanager.php` around line 725.

**Comment by davidhund** [comment]
@ahwayakchih that seems to solve the issue, I can save my entry without errors and the Reflection field is populated correctly.

Using `new EntryManager(Symphony::Engine());` instead of `extension_subsectionmanager::$entryManager->fetch […]` is a current best practice (in 2.2.3)? If so this would probably relate to more code in SSM, correct?

Should this be filed as a bug/fix?

**Comment by ahwayakchih** [comment]
> Using new EntryManager(Symphony::Engine()); instead of extension_subsectionmanager::$entryManager->fetch […] is a current best practice (in 2.2.3)? If so this would probably relate to more code in SSM, correct?

Sorry, but i do not understand. In 2.x branch `extension_subsectionmanager::$entryManager` is created using `EntryManager(Symphony::Engine());`. I saw some changes in HEAD of Symphony, that may indicate implementation of `EntryManager`'s functions as static, but i did not check that yet. If that is true, then we will start using `EntryManager::fetch()` in 2.x branch (maybe also in 1.x branch, but you have to ask **nilshoerrmann** about that :).

**Comment by davidhund** [comment]
@ahwayakchih Ignore me: I do not really know enough about (this) code to really comment on it. My first _assumption_ was that your fix was '_a new way of doing things_' but it was just that: an assumption.

Thanks for the fix: any pointer as to when your `1.x` commits get merged in `master`?

**Comment by nilshoerrmann** [comment]
> Thanks for the fix: any pointer as to when your 1.x commits get merged in master?

I'm ambivalent: it seems like a good idea to either port back a few things and release them as `1.3` or – if we consider the new way of caching items stable – to release `2.0` excluding a few unstable things (like Subsection Tabs). 

@ahwayakchih, you have a better overview over the `2.x` codebase at the moment: What do you think?

**Comment by ahwayakchih** [comment]
**nilshoerrmann**, I still have to work on upgrade script. I think it should be a "must have" for 2.0 release (along with bugfixes, of course :). I will be able to finish it in next 2 or 3 weeks, if thats OK with you.

It also looks like there are some (possibly breaking compatibility) changes comming to Symphony, so it might be good to wait for them and release 2.0 that is up-to-date with Symphony.

So i think it would be better to release 1.3 first.

**Comment by nilshoerrmann** [comment]
Right, so we should have a look at what to back-port beside the fix for this issue. I'd like to take a look at a few UI glitches and also the quantity styles are still missing.

Regarding the possible compatibility issues: Symphony 2.3 is expected around Christmas and a lot of thing will change in the meantime – so our decision shouldn't depend on what we currently know about the next core release.

> I will be able to finish it in next 2 or 3 weeks, if thats OK with you.

Maybe we just wait and see what we'll get done in September – some kind of release around the Symposium sounds good.

**Comment by ahwayakchih** [comment]
> Right, so we should have a look at what to back-port beside the fix for this issue. I'd like to take a look at a few UI glitches and also the quantity styles are still missing.

Quantity is 2.x only, but yeah - it could use some more styling :).

> Symphony 2.3 is expected around Christmas

I've read about changing Managers to more static classes and that it may break few things. Will that be in 2.3 or in next minor point release?

> some kind of release around the Symposium sounds good.

Good idea.

**Comment by nilshoerrmann** [comment]
> I've read about changing Managers to more static classes and that it may break few things. Will that be in 2.3 or in next minor point release?

Everything that has been added to the codebase of the `integration` branch after the release of 2.2.3 is Symphony 2.3 related. There are no additional maintenance releases planned (unless a severe security hole will be found). Check out this post by Brendan: http://symphony-cms.com/discuss/blog/entry/on-the-horizon-symphony-23/

Not sure about this whole static classes/managers thing – it's beyond my PHP skills. I'll wait what the others will come up with.

**Comment by ahwayakchih** [comment]
Thanks for info :).
