### ISSUE TITLE
Duplicate error

### ISSUE THREAD

**Issue by kirkstrobeck** [symphonists/subsectionmanager#159]
Subsection manager cannot detect unique entries with the same data. It makes one or all disappear. Rows should not be checked against data, but against unique entry id.

**Comment by ahwayakchih** [comment]
I can only guess where it cannot detect entries (XML output? Entry edit page?), but if it is about entry not being listed on entry edit page, then it is probablye the same issue as #155.

**Comment by kirkstrobeck** [comment]
Potentially, I guess we'll see if it solves both..

**Comment by kirkstrobeck** [comment]
oops, didnt mean to close..

**Comment by ahwayakchih** [comment]
Should be solved with latest fix for #155.
