### ISSUE TITLE
Usability: focus first form element

### ISSUE THREAD

**Issue by nickdunn** [symphonists/subsectionmanager#16]
This morning I created about 30 entries through Subsection Manager, by copy/pasting text from an email. A little UX tweak that would go a long way would be to give the first input in the sub-section focus when creating a new entry, saving an extra click. The panel slides open, and is primed for data entry.

**Comment by nilshoerrmann** [comment]
That's a good idea. I not sure if this will be possible in a cross-browser way as their behaviour in connections with iframes is somehow strange.

**Comment by nickdunn** [comment]
I don't think the iframe would be an issue. So long as you've got the JavaScript inside the iframe itself (which is possible, since you're already embedding your own CSS when the page is loaded in an iframe) you shouldn't need to communicate across the iframe from the parent page — it'll all be done inside the child page.

**Comment by nilshoerrmann** [comment]
The problem is that you have to set the focus in the parent section. I'll have a look at it but I know that neither Firefox nor Internet Explorer will be my friends here :)

**Comment by nickdunn** [comment]
You could load the child page in the iframe with a `?iframe=true` parameter (or even `#iframe`) and check this with JS inside the child page with JS to set the focus. This way you don't communciate across the iframe, mitigating the usual security/DOM frustrations.

**Comment by nilshoerrmann** [comment]
Ah, I did that in an early version of Mediathek. That works well until the user hit the save button inside the iframe ...

**Comment by nickdunn** [comment]
At which point there need be no auto-focus :-)

**Comment by nickdunn** [comment]
Or... with JS you also append the same GET param to the `<form>` action so it persists after saving.

We did this with a project where we loaded Symphony forms in a lightbox from the frontend (http://drp.ly/FpX9e ) and it worked pretty well.

**Comment by nilshoerrmann** [comment]
Well, that's true. One point for you :)

**Comment by nilshoerrmann** [comment]
> Or... with JS you also append the same GET param to the <form> action so it persists after saving.

That's what I did with Mediathek - it didn't work out well. But I'm sure focussing will work, somehow ...

**Comment by nilshoerrmann** [comment]
Subsection Manager should now [focus the first input field of the subsection](http://github.com/nilshoerrmann/subsectionmanager/commit/ada4e19c9b9e122b0e49860495ca9cbf1562c913).
