### ISSUE TITLE
Keyboard Interactions

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/subsectionmanager#160]
It would be great if Subsection Manager would support rudimentary keyboard shortcuts, e. g. allowing to switch from the search to the results using `↓` and `↑` for navigation – `enter` might be used for selections.

Which shortcuts would be helpful?
Which are the most common interactions?

**Comment by nilshoerrmann** [comment]
PS: It's also the question which of these actions need to be SSM specific and which can be abstracted and implemented in Stage.

**Comment by brendo** [comment]
Tabbing between items attached to a SSM would be nice too!

**Comment by ahwayakchih** [comment]
Maybe items should be wrapped in `a` tag?  If so, should they be "opened" when link is focused?

List of "results" should probably be opened as soon as search box is focused. I think it is "onclick"-only right now.

**Comment by nilshoerrmann** [comment]
I'll close this for now: while I like the idea a lot I'm not a heavy keyboard user myself. If there is a volunteer to tackle this, feel free to post here.
