### ISSUE TITLE
Inline editor opened on drop

### ISSUE THREAD

**Issue by donaldgray** [symphonists/subsectionmanager#161]
I have a parent section (Gallery) which has a Subsection Manager field of type Image.

When I re-order the Images in FF 6.0 on Windows 7 the inline editor is always appearing.

I tried the same actions in Safari, Chrome and IE9 (all on Windows 7) and all drag and drop fine without the inline editor opening.

**Comment by nilshoerrmann** [comment]
I cannot reproduce this using the `2.x` branch – if this issue still occurs after the next release, please post back here.
Closed for now.
