### ISSUE TITLE
HTML not escaping

### ISSUE THREAD

**Issue by kirkstrobeck** [symphonists/subsectionmanager#162]
Still getting HTML in my DS when using multilingual textfield with markdown  
http://see.weareinto.com/AXkE

**Comment by ahwayakchih** [comment]
Just pushed change to 1.x branch. Please test and let us know if it helped, and reopen issue if it did not fix the problem.

Please specify SSM version next time you report a bug :).

**Comment by kirkstrobeck** [comment]
Okay, using the 1.x branch, but it isn't working.  
Anything I need to do other than replace the extension?

**Comment by kirkstrobeck** [comment]
btw, I want to reopen the issue, but I don't have permission.

**Comment by ahwayakchih** [comment]
Did you replace field file too (all extension files, not just extension.driver.php)?

Did you check "HTML-encode text" option in your data-source (i am assuming that you want HTML to be encoded)?

**Comment by kirkstrobeck** [comment]
Yes, I deleted the whole extension folder.  
Is there something I can look for to double-check I have the right files in place?  
Yes, the encode box is checked http://see.weareinto.com/AXqI and http://see.weareinto.com/AWLM

**Comment by ahwayakchih** [comment]
I do not have 1.x version anymore, but 2.x version uses almost the same code in this case, so i tested here with TextBox field (not multilingual), and formatted value was correctly escaped in data-source output.

Could you try the same content but with regular Textarea field? And then maybe with Textbox field? While using the same Markdown formatter of course (so formatted value is exactly the same as in multilingual field).

You can also check if data-source output is not cached anywhere.

**Comment by ahwayakchih** [comment]
> Is there something I can look for to double-check I have the right files in place?

You can check if `field.upload.php` file passes `$encode` instead of `false` to subsection field's `appendFormattedElement` function, just like in the [810e39b](https://github.com/nilshoerrmann/subsectionmanager/commit/810e39b85de465200ef99a973c6fae4eee503114) patch.

**Comment by kirkstrobeck** [comment]
Oh ! 

This did fix it..
https://github.com/nilshoerrmann/subsectionmanager/commit/810e39b85de465200ef99a973c6fae4eee503114

but it wasn't committed to any of the branches I downloaded.
