### ISSUE TITLE
entry list halts after creation

### ISSUE THREAD

**Issue by fawx** [symphonists/subsectionmanager#164]
sym 2.2.3, ssm 1.3, stage 1.3, latest chrome and firefox for linux

i have a subsection with 2 text inputs and 0-5 entries currently.  when i create a new entry the ssm field sits with an animated loading icon indefinitely instead of showing the new entry.

saving the parent entry shows that the subsection entry was properly saved.  there are no javascript errors.

**Comment by fawx** [comment]
i feel like i've either submitted or seen this issue before, so if it's a duplicate, i apologize.

**Comment by nilshoerrmann** [comment]
Moved to #112.
