### ISSUE TITLE
 Allow selection of multiple items issue

### ISSUE THREAD

**Issue by ghost** [symphonists/subsectionmanager#166]
Running Symphony 2.2.3 and Subsection Manager 1.3 but I seem to have problems with one or two of the fields when the setting allow selection of multiple items is not selected.

If you select a subsection from the search and save as normal, then remove the item and save. The item still shows in the <select> and the database even though it should be removed by the button - I'm guessing its within the javascript which unfortunately isn't my strong point - when the page is reloaded the subsection is still selected and can only be deleted directly from the database.

If I select 'allow selection of multiple items' the problem no longer occurs and the remove button works as expected. I've made a start looking into the issue but not sure how much more I can help - will let you know if I pin-point where it may come from though.

Great extension guys, thanks.

**Comment by nilshoerrmann** [comment]
This seems no longer to be an issue in the `2.x` branch.
