### ISSUE TITLE
Order of newly created items isn't saved

### ISSUE THREAD

**Issue by johannahoerrmann** [symphonists/subsectionmanager#17]
I started with a "blank" manager and added one item after another and they were automatically added to the bottom to the list. However, when saving the whole entry, the item order was messed up so that I had to reorder my items manually. This time, the order was saved just fine when saving the entry,

**Comment by nilshoerrmann** [comment]
This should be fixed here: http://github.com/nilshoerrmann/subsectionmanager/commit/084c4d8084a564a8f67cf0018df48d81200437e3
