### ISSUE TITLE
Deleted single entries return after saving entry

### ISSUE THREAD

**Issue by animaux** [symphonists/subsectionmanager#170]
I have an Image Section consisting of an Upload Field and a Text-Caption hooked to an Article-Section via SSM. Only a single image is allowed per article. When I deselect this single Image in the SSM and save the entry, it shows up again.

Symphony 2.2.3
SSM 1.3

[√] Allow creation of new items
[√] Allow selection of items from a list of existing items
[√] Allow deselection of items
[√] Show thumbnail images
[√] Display field’s value in entries table
(other Settings all unchecked)

**Comment by nilshoerrmann** [comment]
Are you sure this is not a required field?

**Comment by animaux** [comment]
I’m positive!

**Comment by nilshoerrmann** [comment]
Fine, negativity isn't a good thing :D

Im Ernst: Was willst Du mir damit genau sagen? Ist das Feld verpflichtend oder nicht?

**Comment by animaux** [comment]
I’m positive! = Ich bin sicher :) 

Sorry, sollte heißen: ich bin sicher, dass es kein verpflichtendes Feld ist.

Here’s a chemist-joke illustrating the meaning of the above idiom:

Two atoms sit in a bar.
First atom: »I don’t feel well at all today, I think I’ve lost an electron.«
Second atom: »Oh my, are you sure?«
First atom: »Yeah, I’m positive!«

_hust_

**Comment by nilshoerrmann** [comment]
Fein, fein :)

I'm not sure why you get the described behaviour – will have to check it. Might take a moment.

**Comment by animaux** [comment]
Cheers, no problem!

**Comment by nilshoerrmann** [comment]
This problem seems to be solved in the `2.x` branch which will be the next release.
