### ISSUE TITLE
Enable shift-click selections.

### ISSUE THREAD

**Issue by kngzero** [symphonists/subsectionmanager#171]
Maybe it's just me, but shouldn't there be a shift-click selection to select a range of entries/items in the dropdown list rather than having to click each one? Perhaps there could be a keyboard short cut as well. I've been using tab + enter to make selecting items easier.

**Comment by nilshoerrmann** [comment]
Yeah, that's a good point. The thing is that SSM currently doesn't use the core selection plugin whereas it should.

Noted as request.

**Comment by nilshoerrmann** [comment]
I just checked if it's possible to switch to Symphony's native selection plugin and there is the problem that Selectable doesn't give the option to always treat a list as range. I'll log an error for Symphony 2.3 to adjust the Selectable plugin accordingly.
