### ISSUE TITLE
Deleting content of the first tab still renders an "Untitled" entry

### ISSUE THREAD

**Issue by johannahoerrmann** [symphonists/subsectionmanager#172]
I have a setup with two tabs, German and English. Both are optional, so I could have a German entry, an English entry or an entry with both languages. I entered text into my first tab, then realized it belonged into the second one so pasted it there and deleted all information from the first tab. Still, on saving, the entry is saved as "untitled" instead of using the second tab's content. I hope this makes sense!

**Comment by nilshoerrmann** [comment]
All tabs now have a clear button to empty a tab. That should fix this issue.
