### ISSUE TITLE
Update on version 2.0

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/subsectionmanager#174]
@ahwayakchih and @brendo:

I decided that it is time to clean-up a few things and get Subsection Manager 2 out until Christmas. This decision comes with a few changes.
- I think providing an updater to map the old sorting with the new one is too error prone. This is a major update so I think it's okay to say that all old sort orders will be lost. An updater can be provided as a standalone script – but I will remove the unfinished bits and pieces that are in the `2.x` branch at the moment.
- I've been debugging a lot of things today and it seem like the new quantities option is causing some weird issues if not used (some for single select managers, others for multiple select managers). The interface for it still needs to be done. I created a [separate `quantities` branch](https://github.com/nilshoerrmann/subsectionmanager/tree/quantities) containing the status quo of the `2.x` branch but I will remove quantities from version `2.0`. It should be added back in version `2.1`.
- Subsection Tabs will loose their ability to create dynamic tabs on the fly. Static tabs will be the only option in this release.

Hope you are fine with this.
So a [merry little Christmas](https://github.com/nilshoerrmann/subsectionmanager/tree/christmas) is in preparation.

**Comment by brendo** [comment]
Yep, fine with me. Make sense to release with as little new features as possible so bugs can be ironed out quicker. It's going to be a very merry Symphony christmas this year :)

**Comment by nilshoerrmann** [comment]
Yes, seems like it – everyone's busy preparing something :)
