### ISSUE TITLE
Subsection entry errors being collapsed

### ISSUE THREAD

**Issue by andrewminton** [symphonists/subsectionmanager#175]
I'm testing the latest SSM on 2.2.5 local install and whenever I attempt to upload an image of the same name or image is too large for the max allowed 2mb default, I should see a notice error as I do in the actual image upload section I've created.

But with SSM I see a quick flash of the message and then the SSM collapses back to show nothing, so I don't see that the entry item has an error and upon save it won't save anything because I didn't see the error.

**Comment by nilshoerrmann** [comment]
What's "latest SSM"? This should be fixed in [2.0 beta 2](https://github.com/nilshoerrmann/subsectionmanager/tree/christmas).

**Comment by andrewminton** [comment]
Ah switched branch and all is ok! thanks.
