### ISSUE TITLE
RAW not working

### ISSUE THREAD

**Issue by kirkstrobeck** [symphonists/subsectionmanager#179]
I pushed the new subsection manager and the website depends on getting @mode='raw' but the new subsection manager doesn't respect the mode setting. It sends @mode='normal' for both.

Any help would be greatly appreciated.

**Comment by nilshoerrmann** [comment]
Which `@mode` are you talking of? I'm not sure I can follow.

**Comment by kirkstrobeck** [comment]
I am referring to http://see.weareinto.com/DvZK — when raw is selected, it still delivers a formatted result ( ie. post-Markdown processing )

**Comment by nilshoerrmann** [comment]
Which field type are you using? I know about `formatted` and `unformatted` as modes.

**Comment by kirkstrobeck** [comment]
multilingual text

**Comment by designermonkey** [comment]
> multilingual text

Are you sure? There is no field with this name registered on the site.

**Comment by kirkstrobeck** [comment]
Multilingual Field => http://symphony-cms.com/download/extensions/view/46066/

Can send formatted or unformatted with a DS. 
Like if it has been processed with Markdown or not.
With the new SSM you can't choose the mode.
