### ISSUE TITLE
Strange queue order 

### ISSUE THREAD

**Issue by johannahoerrmann** [symphonists/subsectionmanager#18]
I just discovered that the queue actually shows the same strange order as my items after saving them for the first time (see issue #17). I can't really tell _how_ the items are ordered in the queue though, as I have a text input with dates as my first field and the first three items show up in the queue like this: 

18.12.2006
15.01.2007
05.02.2007

**Comment by nilshoerrmann** [comment]
Does this issue still exist or has it been fixed together with [bug 17](http://github.com/nilshoerrmann/subsectionmanager/issues/issue/17)

**Comment by johannahoerrmann** [comment]
Not sure, but I can't recreate it, so that's good. If I come across it at some point in the future, I'll make sure to let you know.
