### ISSUE TITLE
Firefox 9: reordering triggers the inline edit interface

### ISSUE THREAD

**Issue by vlad-ghita** [symphonists/subsectionmanager#181]
In FF 9, when dragging an item down (reordering), after releasing the mouse-button, the inline edit interface is triggered.<br />
When dragging an item up, it's fine.

In Chrome it's working fine.

**Comment by nilshoerrmann** [comment]
I thought I fixed that a while back. There have been a few merging problem can you verify if this is still an issue with the latest release (2.1.2)? Thanks!

**Comment by nilshoerrmann** [comment]
This shouldn't be a problem anymore using version 3.0beta on Symphony 2.3.
