### ISSUE TITLE
IE8 and IE9 inline "create new" error

### ISSUE THREAD

**Issue by frenkel** [symphonists/subsectionmanager#182]
Hi,

First of all, thanks for this great extension!
I client of mine is having an issue though. Using IE8 or IE9 he'll get an error when saving a subsection. The error is something like this:
Permission denied
jquery.js
URI: http://XXXX/symphony/assets/jquery.js
Line: 107
Char: 40

Permission denied
jquery.js
Line: 24

This will result in the gray "loading screen" to stay put, although the subsection is saved without a problem.

Thanks in advance!

**Comment by nilshoerrmann** [comment]
When you see the loading spinner, the `iframe` displaying the subsection is just hidden via CSS. Could you please have a look at the page's source and see if an error is displayed in that hidden `iframe`?

**Comment by frenkel** [comment]
No, it has "entry created just now" on top and the form is shown filled in.

**Comment by nilshoerrmann** [comment]
I'm not sure how this might be related to the error you are getting in the console but from what you describe it seems like IE9 interprets line 230 of `subsectionmanager.publish.js` in a wrong way. What happens if you change the selector to `.success` (removing the id `#notice`)?

**Comment by frenkel** [comment]
Doesn't help unfortunately. Still the error and the box stays visible.

**Comment by nilshoerrmann** [comment]
Does this only happen for new entries or for edited entries as well?

**Comment by frenkel** [comment]
Also when editting.

**Comment by nilshoerrmann** [comment]
What's the output in your console when you add these line before line 230?

```
console.log(content);
console.log(content.find('#notice.success').length);
```

**Comment by frenkel** [comment]
The output is:
LOG: [object Object]
LOG: 0

I also tries content.find('.success') with the same result: length 0, no elements found.
Thanks for the fast replies :)

**Comment by nilshoerrmann** [comment]
Hm, okay, thanks for the results – I will have to do some more testing on my local install but I won't have the time for that today.

**Comment by nilshoerrmann** [comment]
For your information: 
- [Discontinuing Support for Subsection Manager](http://getsymphony.com/discuss/thread/83270/7/#position-121)
- [Investigating Relationships](http://getsymphony.com/discuss/thread/96191/)
