### ISSUE TITLE
MySQL Error (1271): Illegal mix of collations for operation 'UNION' in query

### ISSUE THREAD

**Issue by tonyarnold** [symphonists/subsectionmanager#185]
```

MySQL Error (1271): Illegal mix of collations for operation 'UNION' in query "(SELECT t1.`subsection_id`, t1.field_id
         FROM `sym_fields_subsectionmanager` AS t1
          INNER JOIN `sym_fields` AS t2
          WHERE t2.`element_name` = 'sidebar-image'
           AND t2.`parent_section` = '38' 
         AND t1.`field_id` = t2.`id`
          LIMIT 1)
       UNION
        (SELECT t1.`subsection_id`, t1.field_id
          FROM `sym_fields_subsectiontabs` AS t1
         INNER JOIN `sym_fields` AS t2
          WHERE t2.`element_name` = 'sidebar-image'
           AND t2.`parent_section` = '38' 
         AND t1.`field_id` = t2.`id`
          LIMIT 1)
       LIMIT 1"
```

I'm seeing this when querying a datasource containing an subsection that only allows a single entry. What information can I provide to help track this down (and potentially fix it myself). I don't know enough about SSM at this point to make an educated guess :(

**Comment by brendo** [comment]
It means the two tables have been created in different encodings. You'll probably find one is `latin1` and one is `utf8`. 

Curiously, this has been occurring more of late I can't pick why as there have been no core level changes to trigger this. Perhaps we are just at that tipping point where half the extensions specify UTF8 and half specify nothing.

Or it might coincide with a recent MySQL update.

**Comment by tonyarnold** [comment]
That was exactly it. I think I went the wrong way and removed the specified collation from the tables being compared, but it works now.

**Comment by nilshoerrmann** [comment]
Just so I get this right: this is not a problem caused by Subsection Manager? It's either caused by Symphony or manual database changes?! I'm a bit confused at the moment.

**Comment by tonyarnold** [comment]
It's not SSM. It does need addressing, but it's a bit of a manual change for everyone who is including SQL in their extensions.

I'll need to get @brendo to explain it in a way that makes sense — basically, MySQL defaults are conflicting with the SQL in some extensions (depending on your MySQL server's configuration) which specify strict collations. It's not really my area of expertise, so I'd need to do more reading to not make a balls-up of the explaining.

**Comment by nilshoerrmann** [comment]
Additional question: Are you using an build that has been updated from Subsection Manager 1 to 2? In this case the tables `sym_fields_subsectionmanager` (version 1) and `sym_fields_subsectiontabs` (version 2) would have been created at different times – maybe this is a source of this problem?

**Comment by tonyarnold** [comment]
Good call: yes, I am. I updated it today. That could definitely be the cause of the collation changes.

**Comment by ganeshpaiya** [comment]
Illegal mix of collations for operation
