### ISSUE TITLE
Updating from 1.0.1 to 2.1.2

### ISSUE THREAD

**Issue by kanduvisla** [symphonists/subsectionmanager#186]
I tried updating from SSM 1.0.1 to 2.1.2, but I got an SQL-error.

It worked when updating from 1.0.1 to 1.3.2 and from there to 2.1.2, but it should be something to look in though...

**Comment by nilshoerrmann** [comment]
Could you provide me with a bit more information? What kind of SQL error did you get?

**Comment by kanduvisla** [comment]
Something about a table or field that didn't exist. As mentioned, I managed to update it by making a step in-between, so I didn't copy/pasted the error-message.

**Comment by kanduvisla** [comment]
Had another site I'm updating from 1.0.1 to 2.1.2. This is the error:

```
MySQL Error (1054): Unknown column 'allow_multiple_selection' in 'btr_fields_subsectionmanager' in query "ALTER TABLE `btr_fields_subsectionmanager` CHANGE COLUMN `allow_multiple_selection` `allow_multiple` tinyint(1) default '0'"
```

**Comment by nilshoerrmann** [comment]
For your information: 
- [Discontinuing Support for Subsection Manager](http://getsymphony.com/discuss/thread/83270/7/#position-121)
- [Investigating Relationships](http://getsymphony.com/discuss/thread/96191/)
