### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by quma** [symphonists/subsectionmanager#187]
Hallo Nils,

sorry wegen meinem schlechten englisch schreibe ich mal in deutsch.

Symphony 2.2.5
Subsection Manager 2.1.2

Ich wollte in die "Artikel-Sektion" mit der "Subsection Tabs - Funktion" die "Metainfo Sektion" in einem Tab einbinden.
Dazu habe ich in den Feld Einstellungen als Unterbereich die "Metainfo" Sektion ausgewählt und in das Feld "Tab names" "Artikel, Metainfo" eingegeben.

Jetzt erscheinen die beiden Tabs auch in der Artikel-Sektion allerdings sind die Inhalte beider Tabs identisch d.h. die Metainfos sieht man sowohl im Tab Artikel als auch Metainfo.

Handelt es sich dabei um ein Fehler oder habe ich etwas an der Handhabung dieser Funktion etwas grundlegend falsch verstanden ?

Danke

**Comment by nilshoerrmann** [comment]
Ich glaube, da handelt es sich um ein Missverständnis, was die Tabs machen: sie sind ein Hilfsmittel um mehrere gleichartige, sich von der Struktur wiederholende Inhalte einem Elterneintrag hinzuzufügen. Zum Beispiel, wenn es um mehrsprachige Einträge geht, die aus einem Titel und einem Text bestehen.

Wenn Du, ich hoffe ich habe das richtig verstanden, bestimmte Informationen in Tabs "auslagern" willst, brauchst Du eine andere Erweiterung: suche mal nach Nick Dunns Publish Tabs. Die machen meines Erachtens das, wonach Du suchst.

**Comment by quma** [comment]
Ja, da habe ich wohl die Funktion missverstanden.

Allerdings finde ich die Idee recht gut und würde mir das als zukünftige Funktion wünschen.

Ich weiß zwar das dass auch mit der normalen Subsektion-Funktion und Nick Dunns Publish Tabs geht, allerdings schmiedet sich die über die Tabs angezeigte Unterbereiche viel besser in das Layout der eigentliche Sektion ein.

Eventuell könntest du den Subsektion Manager mit einigen Anzeige-Funktionen erweitern z.B.
- Zeige Unterbereich eingebettet in der Sektion an. 

Wählt man diese Funktion aus wird die Sektion ähnlich wie bei deiner Tab-Funktion eingebettet angezeigt.

Am besten gebe ich dir mal ein Beispiel was machen möchte,

Ich habe eine Sektion Artikel und eine eigene Sektion zum verwalten der Meta Keywords.
Zum einen möchte ich die beiden Sektionen miteinander verbinden, was ja bereits möglich ist.
Und zum anderen würde ich gerne die Meta Keywords Sektion als Unterbereich eingebettet in der Artikel-Sektion anzeigen.

Es ist also möglich komfortabel die MetaKeywords entweder direkt beim bearbeiten des Artikels anzulegen oder eben über die Meta Keywords-Sektion.

Jedes mal wenn ich einen neuen Artikel erstelle kann ich auch gleich die Meta Keywords anlegen und zu einem späteren Zeitpunkt bearbeiten /abändern. Es ist also immer nur ein Eintrag der Artikel-Sektion  mit einem Eintrag der MetaKeywords-Sektion verbunden. In diesem Fall macht es aus meiner Sicht durchaus Sinn den Unterbereich eingebettet anzuzeigen ohne die sonst üblichen Sektions Manager Funktionen.

Zudem würde solch eine Funktion es erlauben, dass man eine Sektion erstellt die mehr oder weniger komplett aus anderen Sektionen besteht sprich zusammengesetzt ist.

Ich hoffe du konntest mir folgen :)

**Comment by nilshoerrmann** [comment]
Aber ist das nicht längst möglich, wenn Du Publish Tabs verwendest und den Tab für die Keywords einen Subsection Manager setzt? Wenn das Problem hauptsächlich die Darstellung des Tab-Interfaces von Nicks Erweiterung ist, dann würde ich eher das Styling dort anpassen – der Sinn und Zweck dieses spezifischen Modus für den Subsection Manager erschließt sich mir zumindest nicht: es müsste ja eine Funktion sein, die möglichst allgemein verwendbar ist und sonst nicht realisierbar ist, um eine Ergänzung zu rechtfertigen. Das sehe ich zur Zeit nicht.
