### ISSUE TITLE
Copy when no items are available

### ISSUE THREAD

**Issue by johannahoerrmann** [symphonists/subsectionmanager#188]
> There are currently no items available. Perhaps you want create one first?

With no items available in the queue, the same copy is shown when creation of new items is allowed - or not allowed. In the latter scenario, the second sentence reads somewhat misleading, as I can't create new items right where I am.

**Comment by nilshoerrmann** [comment]
This copy doesn't exist anymore in version 3.0beta on Symphony 2.3.
