### ISSUE TITLE
Newly created item stuck in queue

### ISSUE THREAD

**Issue by johannahoerrmann** [symphonists/subsectionmanager#19]
I created a new item while my queue was visible ("browse"). It was added to the bottom of the queue but was not added to my selection. It showed a delete button on the right hand side which didn't work though, and it couldn't be selected to add it to my selection either. I had to delete it in my original section to get rid of it.

[Screenshot of what it looked like](http://projekte.johannahoerrmann.de/screenshots/new-item-stuck-in-queue.png)

**Comment by johannahoerrmann** [comment]
Edit: The item behaved normally after saving the whole entry (= no button next to it, I could add it to my selection and delete it)

**Comment by nilshoerrmann** [comment]
That makes perfectly sense: It seems like there is still a bug after creating new items. They are created and saved correctly but the JavaScript fails to add them in the correct place. After saving the Subsection Manager is built from scratch using the saved database information (which has been correctly updated) and thus the manager creates a working list again.

**Comment by nilshoerrmann** [comment]
> I created a new item while my queue was visible ("browse").

Interesting -- it seems like everything works just fine when the queue (or the browser) has been closed while clicking `Create New`. The automatic addition of newly created items only fails when the queue has been open.

**Comment by nilshoerrmann** [comment]
Ah, scratch that - it just doesn't always work: sometime it does, sometime it doesn't. Strange ... I'll investigate that problem.

**Comment by nilshoerrmann** [comment]
Okay, this seems to be a problem with jQuery `.replaceWith()` function.

**Comment by nilshoerrmann** [comment]
This should be fixed [here](http://github.com/nilshoerrmann/subsectionmanager/commit/b500f7cd2f067f87cf99a242e74c228e00e9911e) and [over there](http://github.com/nilshoerrmann/stage/commit/ef68ced70174f15be221b8371e354f054c650283).
