### ISSUE TITLE
Problem when deleting entry with Subsection Tabs

### ISSUE THREAD

**Issue by frenic** [symphonists/subsectionmanager#193]
Database error when deleting an entry containing data from Subsection Tabs.

Problem found on extension.driver.php row #412. Just replace it with:

```
FROM `tbl_entries_data_" . $field_id[0] . "`
```

**Comment by nilshoerrmann** [comment]
For your information: 
- [Discontinuing Support for Subsection Manager](http://getsymphony.com/discuss/thread/83270/7/#position-121)
- [Investigating Relationships](http://getsymphony.com/discuss/thread/96191/)
