### ISSUE TITLE
Select Box goes under SSM header

### ISSUE THREAD

**Issue by PascalPiche** [symphonists/subsectionmanager#196]
If you have a Select Box Just before a SSM, when the select box opens, it goes under some div in the SSM.

I have this usign the better forms extension and SSM 2.1.2.

See http://picpaste.com/Untitled-1_1.jpg

**Comment by nilshoerrmann** [comment]
This has to do with the different z-indexes used by both extensions – in this case better forms needs to set a higher value than Subsection Manager. So it should be fixed in Simone's extension.
