### ISSUE TITLE
[3.0beta] Stage not found

### ISSUE THREAD

**Issue by jensscherbl** [symphonists/subsectionmanager#197]
```
Fatal error: Class 'Stage' not found in /symphonycms/extensions/subsectionmanager/extension.driver.php on line 409
```

**Comment by nilshoerrmann** [comment]
Uncommenting that line should solve the problem – Stage is no longer needed in Symphony 2.3.

**Comment by jensscherbl** [comment]
There are still a lot more references to stage in your code.

**Comment by nilshoerrmann** [comment]
In this case I guess something must have gone wrong during merging my branches locally. Will check this.
There should be code to _remove_ Stage but no call to the class itself.

**Comment by nilshoerrmann** [comment]
This should be fixed now.

**Comment by jensscherbl** [comment]
Thanks, will test it later.
