### ISSUE TITLE
[3.0beta] Image Preview not working in 2.3rc1

### ISSUE THREAD

**Issue by animaux** [symphonists/subsectionmanager#198]

**Comment by nilshoerrmann** [comment]
What does that mean exactly? Do you get a broken image or no image at all?

**Comment by animaux** [comment]
Sorry. Yes, broken image. The Image URL looks ok. 

`<img src="http://archiv.animaux.de/bildarchiv/image/2/40/40/5/img/sammlungen/kurt-schindler.jpg" width="40" height="40" class="handle">`

Possibly rather an issue with JIT?

The same happens with the `Image Index Preview`-extension (I know it’s not 2.3 compatible yet).

**Comment by animaux** [comment]
I can get the pictures displayed by doing the following:
- copy the JIT image url
- load it in a new tab/window
- reloading this URL makes it show up the first time
- reloading the backend page then show the image

I’m pretty sure this is some JIT-related issue, so I’m cling this, sorry to bother you again Nils :·)

**Comment by nilshoerrmann** [comment]
Lösch doch mal Deinen Cache-Ordner im `manifest`, vielleicht hilft das schon. Wir hatten neulich ein ähnlich Problem lokal mit JIT, weil nicht genügend Speicher freigegeben war.

**Comment by animaux** [comment]
Danke!
