### ISSUE TITLE
Drag and drop file paths are wrong

### ISSUE THREAD

**Issue by michael-e** [symphonists/subsectionmanager#2]
The "drag and drop file paths" as well as the displayed file paths (using the {$file} parameter in the subsection manager field setting) are missing the "workspace" part. So Markdown links won't work at all. 

This can be seen in the [Forum discussion](http://symphony-cms.com/discuss/thread/41122/1/#position-1) as well.

**Comment by nilshoerrmann** [comment]
Good catch. Michael, wir sollten Dir den Titel "Fehlerfinder" verleihen :)

**Comment by michael-e** [comment]
Ja, gib mir keine Software. Ich klicke und es ist kaputt...

Don't give me software. I can kill it on the first click.

:-)

**Comment by nilshoerrmann** [comment]
Nee, das ist prima. So muss es sein. So please go along!

**Comment by nilshoerrmann** [comment]
[Fixed here](http://github.com/nilshoerrmann/subsectionmanager/commit/42c9a25b692a828f377fcdf54be50b31119ecabb).

**Comment by michael-e** [comment]
Drag and drop works. But the displayed path still omits the "workspace" part. Is this wanted?

It's a just a bit irritating because the path starts with a slash. But, if the path started with "/workspace", it still would be somehow strange if Symphony is in a subdirectory. So you might think about leaving it as it is ("path in workspace folder"), and just remove the leading slash.

**Comment by nilshoerrmann** [comment]
It's intentionally - it's not perfect (I know). Other opinions?

**Comment by michael-e** [comment]
It's good as it is because those paths won't be unnecessarily long. Just: To slash or not to slash, that is the question. :-)

**Comment by nilshoerrmann** [comment]
Then we'll stick this the slash as this is the way Symphony stores the file path in the database.

**Comment by michael-e** [comment]
That's a good reason. Convinced.
