### ISSUE TITLE
List items in SSM too long

### ISSUE THREAD

**Issue by hypnosis** [symphonists/subsectionmanager#204]
When i clicked on search panel without any string, it show me all 300 items, i have.

**Comment by nilshoerrmann** [comment]
Sorry to say but this is a feature and not a bug.

**Comment by hypnosis** [comment]
It is too slow when all items are opening. I have sections with 600 items linked with subsectionManager with other. It is main reason, why i still use 2.2.5 symphony with SSM 2.

**Comment by nilshoerrmann** [comment]
There is one difference: SSM 2 asynchronously fetches items when the document is ready, SSM 3 does so when you start searching. It should be ready instantly when you open the search a second time. Can you confirm this?
