### ISSUE TITLE
Hold search results opened after selected any item

### ISSUE THREAD

**Issue by hypnosis** [symphonists/subsectionmanager#206]
Hold search results opened after selected any item. It close after select any item, it is not usable. The UX in SSM 2.2.x was more usable.

**Comment by nilshoerrmann** [comment]
The question is when does the search need to stick open? I can only think of one situation: adding multiple items. My idea is to add a multiple select option, triggered by holding `shift` (similar to how selecting in the index tables of the backend works). But I haven't found the time to implement this.

Would that solve your problem?

**Comment by hypnosis** [comment]
You are absolutely right, Adding multiple items requires search results opens.
Holding shift or the same functional keys can solve this problem.
