### ISSUE TITLE
Missing preferences

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/subsectionmanager#21]
It should be possible to set the options for dragging, sorting, searching and creating of items in the preferences directly.

**Comment by nilshoerrmann** [comment]
Maybe queue highlighting should be an option, too.

**Comment by klaftertief** [comment]
What about a _Custom drop text_ option? This way you can define special tags/text for some fancy ninja XSLT. I'm thinking about something like `IMAGE: 123, left|center|right`.

**Comment by nilshoerrmann** [comment]
Version 1.0 final will store all Stage settings in the database and will offer an interface to the user in the section preferences.

A custom drop text will be introduced in a later version of the extension and will not be part of 1.0 final.

**Comment by nilshoerrmann** [comment]
Custom drop texts will be introduced in version 1.1.
