### ISSUE TITLE
Does not output other values apart from IDs

### ISSUE THREAD

**Issue by zooshme** [symphonists/subsectionmanager#210]
Hi I'm using Subsection Manager 3 beta with Symphony 2.3 

I've noticed that the output XML for the items in a Subsection list does not include any other values apart from the IDs of those items. 

Thanks,
Ovi

**Comment by nilshoerrmann** [comment]
Maybe related to #199.

**Comment by zooshme** [comment]
Thank you Nils. Solution in #199 solved my problem.
