### ISSUE TITLE
MySQL Error: Table 'symphony.sym_fields_stage' doesn't exist

### ISSUE THREAD

**Issue by petsagouris** [symphonists/subsectionmanager#211]
I got 

```
MySQL Error (1146): Table 'symphony.sym_fields_stage' doesn't exist in query: SELECT SQL_CACHE COUNT(*) FROM `sym_fields_stage`
```

When trying to uninstall (_gasp!_) the extension. This happens in RC3.
Deactivating does not trigger such error.

**Comment by nilshoerrmann** [comment]
Does is work if you replace [these lines](https://github.com/hananils/subsectionmanager/blob/master/extension.driver.php#L641-646) with this code?

```
// Remove old Stage tables if they are empty
if(!empty(Symphony::Database()->fetch("show tables like 'tbl_fields_stage'"))) {
    $count = Symphony::Database()->query("SELECT COUNT(*) FROM `tbl_fields_stage`");
    if($count == 0) {
        Symphony::Database()->query("DROP TABLE IF EXISTS `tbl_fields_stage`");
        Symphony::Database()->query("DROP TABLE IF EXISTS `tbl_fields_stage_sorting`");
    }
}
```

**Comment by petsagouris** [comment]
Thanks, gonna try that as soon as possible and report back.

**Comment by nilshoerrmann** [comment]
Thanks a lot lot, that would be nice.

**Comment by petsagouris** [comment]
Ok, it seems that [you can't use empty() with anything else other than a variable](http://stackoverflow.com/a/1075559/140734).

So I went ahead and fixed the snippet you provided on your last comment like so: 

```
// Remove old Stage tables if they are empty
$tbl_fields_stage_exists = Symphony::Database()->fetch("show tables like 'tbl_fields_stage'");
if( ! empty($fields_stage_table_exists) ) {
    $count = Symphony::Database()->query("SELECT COUNT(*) FROM `tbl_fields_stage`");
    if($count == 0) {
        Symphony::Database()->query("DROP TABLE IF EXISTS `tbl_fields_stage`");
        Symphony::Database()->query("DROP TABLE IF EXISTS `tbl_fields_stage_sorting`");
    }
}
```

Which promptly notifies that:

```
MySQL Error (1146): Table 'symphony.sym_fields_stage_sorting' doesn't exist in query: DELETE FROM `sym_fields_stage_sorting` WHERE `context` = 'subsectionmanager'
```

Which basically is a logic error for which I can't come up with an answer for since I don't know exactly how this extension works. It is a logic error in the situation that the `tbl_fields_stage` exists, the `tbl_fields_stage_sorting` gets dropped, and then later on the last instruction of the function there is a `DELETE` query executed on it.

**Comment by nilshoerrmann** [comment]
What about this:

```
try {
    $count = Symphony::Database()->query("SELECT COUNT(*) FROM `tbl_fields_stage`");
    if($count == 0) {
        Symphony::Database()->query("DROP TABLE IF EXISTS `tbl_fields_stage`");
        Symphony::Database()->query("DROP TABLE IF EXISTS `tbl_fields_stage_sorting`");
    }
} catch (Exception $e) {}
```

**Comment by nilshoerrmann** [comment]
>    MySQL Error (1146): Table 'symphony.sym_fields_stage_sorting' doesn't exist in query: DELETE FROM `sym_fields_stage_sorting` WHERE `context` = 'subsectionmanager'

[Line 654](https://github.com/hananils/subsectionmanager/blob/master/extension.driver.php#L654) just needs to be removed. It's old code I forgot to delete.

**Comment by petsagouris** [comment]
Ok, replaced the lines as per your last snippet and removed the last instruction of the function and the extension now uninstalls without problems. I'd do a pull request but its all your work on this issue ;)
