### ISSUE TITLE
Feature Request - relationship

### ISSUE THREAD

**Issue by quma** [symphonists/subsectionmanager#212]
Display relationship in entries table

**Comment by klaftertief** [comment]
I'll have a look at it later this week, it was mentioned a couple of times in the last time.

**Comment by nilshoerrmann** [comment]
Danke, Jonas! 

It would be nice to make displaying the relationship an optional feature in the field settings. And I'm not sure if it would be possible to offer different settings based on the data stored: like displaying the relationship in the parent section or displaying it in the child section or both?

**Comment by klaftertief** [comment]
It'll be optional, like in the SBL via a setting "Display relationship in entries table". I don't really get your question though. Can't you already show the relationships in the parent section via the normal "Display in entries table" setting? But this could be modified to link to the child entries, maybe with an additional setting.

**Comment by nilshoerrmann** [comment]
I was thinking of a select box instead of a checkbox:
- Don't display
- Display relationship in parent section
- Display relationship in child section
- Display relationship in parent and child section

> Can't you already show the relationships in the parent section via the normal "Display in entries table" setting?

Not in the default Symphony way that is showing a linked count.

**Comment by klaftertief** [comment]
But wouldn't it be better to use as much default functionality for a consistent UI and to not re-invent the wheel?

**Comment by nilshoerrmann** [comment]
Well, yes, sure. But so far relationship management in Symphony was always based on reinventing stuff.

**Comment by klaftertief** [comment]
Just wanted to let you know that I've got the basics working. Will clean it up soonish and push it then.

**Comment by nilshoerrmann** [comment]
Jonas, did you make any progress in this matter?

**Comment by klaftertief** [comment]
Sorry, got sidetracked. Do you have an ETA for a next version? Still need to clean it a little. And I haven't looked into an updater script.
