### ISSUE TITLE
Feature Request - with Theme

### ISSUE THREAD

**Issue by quma** [symphonists/subsectionmanager#213]
Subsectionmanager 3

Is that possible to integrate a withe theme ?
I think the dark theme is to extreme.

thx

**Comment by nilshoerrmann** [comment]
I'm not planning to include themes but you could send a pull request with the needed changes. Steps involved:
- add a theme setting (I guess this should be done globally, so it should go into the configuration)
- optionally remove the class `.dark` from the Duplicator interface
- make sure the the dark scheme is only applied when the class `.dark` is present
