### ISSUE TITLE
Can't create new subsection entries

### ISSUE THREAD

**Issue by designermonkey** [symphonists/subsectionmanager#216]
Using 3 beta2, I can't interact with the iframe displayed form.

**Comment by designermonkey** [comment]
It is down to the settings. I have selected `Allow creation of new items` but if `Allow editing` is not selected too, the form becomes read only when trying to add new items.

**Comment by nilshoerrmann** [comment]
Ah, right. This is an oversight when I switched from Stage to Duplicators: new instances no longer have the class `new` attached. Not sure what the easiest solutions is. Maybe adding the class new to the templates `header` and checking this [here](https://github.com/hananils/subsectionmanager/blob/master/assets/subsectionmanager.publish.js#L210) would be an idea: the header get's replaced with the actual content when the new item is saved.
