### ISSUE TITLE
Filtering by Select Box Link

### ISSUE THREAD

**Issue by designermonkey** [symphonists/subsectionmanager#217]
Ok. So I've made some progress on this today by adding the Select Box Link in as an option, and re-jigging the PHP a little bit to correctly get the options available from the SBL field.

Now I have some questions regarding the state of the SSM in beta, as I don't know if my issues are related to what I've done, vs the beta status.
1. I can't see any existing options available for me to select from, even if I have the search form `on` as an option.
2. Should the select box in a new child entry be pre-populated with the specified filter option from the settings? Mine isn't.

**Comment by nilshoerrmann** [comment]
Subsection Manager is considered stable on 2.3, Subsection Tabs is still broken – hence the beta status.

> 1. I can't see any existing options available for me to select from, even if I have the search form on as an option.

It's working for me on different installs with different complexities so I guess this is related to your filtering changes.

> 1. Should the select box in a new child entry be pre-populated with the specified filter option from the settings? Mine isn't.

SSM never pre-populated the select box of an instance it was filtered with – I always considered this a missing feature but never found the time to fix it.
