### ISSUE TITLE
Widescreen mode

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/subsectionmanager#22]
[See related forum discussion](http://symphony-cms.com/discuss/thread/41122/2/#position-35).

**Comment by nickdunn** [comment]
Woo! Glad it's being considered as a feature request.

I did something similar, but altogether much simpler, in Map Location and/or Entry Revisions whereby I tweaked the style slightly depending on the column. For the above it was just a case of swapping whether the tabs sat top-left or top-right.

**Comment by nilshoerrmann** [comment]
I think it's a cool idea. Not sure about the position of the different panels etc. but I will think about that. Mockups, code or whatever are highly welcome.

Thinking about a the further development I think this should be the first thing to do after release version 1.0.

**Comment by nilshoerrmann** [comment]
This needs to be a Stage option. Moved discussion to the correct place: https://github.com/nilshoerrmann/stage/issues/issue/4
