### ISSUE TITLE
Removing field from a section doesn't works

### ISSUE THREAD

**Issue by mblabs** [symphonists/subsectionmanager#221]
I've searched in the issues but never founding, so... When I try to remove the field form a section, after saving it disappears in the section manager, but when I try to insert a new entry in the updated section the SSM field shows again (only in the entry manager).

**Comment by nilshoerrmann** [comment]
What do you mean by saying the "field shows up again"?

**Comment by designermonkey** [comment]
I have seen this today too. I edited three sections to remove SSM fields, and after save, when I went to add an entry to each section, the SSM was still there. When going back to the Section editor, the field was present again.
