### ISSUE TITLE
Search negative margin-top causing overlap

### ISSUE THREAD

**Issue by DavidOliver** [symphonists/subsectionmanager#226]
### Settings to reproduce

`Allow creation of new items`: not checked

`Show search`: checked
### Result

![Search negative margin-top causing overlap](http://dl.dropbox.com/u/183085/symphonycms/ssm-search.png)
### Browsers affected

Firefox and Webkit/Chromium

**Comment by designermonkey** [comment]
Aha! @DavidOliver has already logged it. Saves me the time ;o)

**Comment by designermonkey** [comment]
Changing that margin to -5px fixes it. Any lower, or positive values, or a value of `0` breaks the dropdown autocomplete, which then appears at the top of the select-box

**Comment by nilshoerrmann** [comment]
> Any lower, or positive values, or a value of 0 breaks the dropdown autocomplete, which then appears at the top of the select-box

Sidenote: If there is not enough space below the select box, the dropdown should appear above.

**Comment by designermonkey** [comment]
Yeah, I spotted that, problem being that moving the margin to a positive value causes this to always show above.
