### ISSUE TITLE
Styling Issues

### ISSUE THREAD

**Issue by designermonkey** [symphonists/subsectionmanager#227]
version 3beta, I have styling issues:

![](http://i.imgur.com/RMdgl.png)

**Comment by azzagazz** [comment]
same here. has someone been able to fix this? i know that the extension has been deprecated but it would be nice to have the interface working.

**Comment by nilshoerrmann** [comment]
It's either a missing negative `margin-top` or a missing negative `top` positioning.

**Comment by azzagazz** [comment]
hi nils, 

thanks for the reply. i noticed that in my installation the top-margin was commented. 

`.field-subsectionmanager .constructable + .browser {
    /*margin-top: -30px;*/
}`

thanks,
daniel
