### ISSUE TITLE
Unencoded ampersands results in invalid backend HTML

### ISSUE THREAD

**Issue by nickdunn** [symphonists/subsectionmanager#23]
When writing out the hidden `<select>`, values for each option are not sanitised. This results in invalid HTML markup, and will break extensions such as Publish Filtering and Section Schemas which attempt to parse this markup using XPath.

The solution seems to be in `class.subsectionmanager.php`, line 170:

```
$options[] = ... General::sanitize($field_value));
```

**Comment by nilshoerrmann** [comment]
[Fixed](http://github.com/nilshoerrmann/subsectionmanager/commit/d5bf36164b53fc36cd2df35184913743b75d8c98).
