### ISSUE TITLE
Layout problem with new items

### ISSUE THREAD

**Issue by animaux** [symphonists/subsectionmanager#236]
On creation of new items the item content is stuck under the header.

![bildschirmfoto 2013-07-25 um 08 23 16](https://f.cloud.github.com/assets/446874/853898/c20abf5c-f4f2-11e2-938a-63b63ce2aea9.png)

(A workaround is to use the Tab-Key to navigate to the hidden item, which in turn fixes the layout.)

![bildschirmfoto 2013-07-25 um 08 23 25](https://f.cloud.github.com/assets/446874/853899/c5a57e36-f4f2-11e2-9950-d8007526ffdd.png)

**Comment by nilshoerrmann** [comment]
Welches Element ist denn hochgescrollt? (Es gibt [3 oder 4](https://github.com/hananils/subsectionmanager/blob/master/assets/subsection.publish.css#L12-L29) mit `overflow: hidden;`, die in Frage kommen.)

**Comment by animaux** [comment]
`<div id="wrapper">` ist das letzte Element welches richtig sitzt.

`<div id="contents">` ist dann das erste welches hochgerutscht ist.

![bildschirmfoto 2013-07-25 um 08 46 40](https://f.cloud.github.com/assets/446874/854001/0720ba3a-f4f6-11e2-9b52-3b15fad8d220.png)

![bildschirmfoto 2013-07-25 um 08 46 50](https://f.cloud.github.com/assets/446874/854002/0a7df0ee-f4f6-11e2-9efe-fdb3beb6936a.png)

**Comment by yojeek** [comment]
Was this fixed? I still experience similar problem when adding/editing items:

![ssm-height-miscalculation](https://f.cloud.github.com/assets/464535/1300191/bf67f44c-310e-11e3-9309-0c93d7e3fad1.png)

Issue may be related to https://github.com/hananils/subsectionmanager/issues/235.

Ubuntu FF/Chromium, Symphony 2.3.3, SSM 3.5.1 .

**Comment by nilshoerrmann** [comment]
You are not experiencing this issue but #235 which _should_ be fixed.
Are you using the latest version and have you emptied your browser's cache?
