### ISSUE TITLE
Version 3.5.1 still contains few references to _subsectiontabs

### ISSUE THREAD

**Issue by timteka** [symphonists/subsectionmanager#239]
Version 3.5.1 still contains few references to _subsectiontabs

**Comment by nilshoerrmann** [comment]
That might well be. But where?

**Comment by timteka** [comment]
with UNION in getting $id on line 230 in extension.driver :-)
sorry, but with it add-on is complete unusable in frontend (though the backend functions properly)

**Comment by nilshoerrmann** [comment]
Are you sure you've got the latest code?

**Comment by timteka** [comment]
Oops, sorry. It was already implemented by Implemint ("11 days ago Removing union query to old tab functionality").
Seems like i've downloaded kind of cached obsolete version :-(

**Comment by nilshoerrmann** [comment]
No problem. Hope updating solves your issue!

**Comment by nilshoerrmann** [comment]
I just released a new version, this should clear up things a bit:
https://github.com/hananils/subsectionmanager/releases/tag/3.5.2
