### ISSUE TITLE
Cannot use a scalar value as an array

### ISSUE THREAD

**Issue by tonyarnold** [symphonists/subsectionmanager#24]
I'm getting the following error under Symphony 2.0.8 when saving the parent entry (the subsection seems to save fine and is composed of a single Unique Upload Field).

```
Cannot use a scalar value as an array
/Users/tonyarnold/Sites/tonyarnold.local/extensions/subsectionmanager/fields/field.subsectionmanager.php line 444

439      * @param string $mode
440      */
441     public function appendFormattedElement(&$wrapper, $data, $encode = false) {
442
443         // unify data
444         if(!is_array($data['relation_id'])) $data['relation_id'] = array($data['relation_id']);
445
446         // create Subsection Manager element
447         $subsectionmanager = new XMLElement($this->get('element_name'));
448
```

**Comment by nilshoerrmann** [comment]
Are you still experiencing this issue using Symphony 2.0.8RC2?

**Comment by tonyarnold** [comment]
To be honest, Nils, I stopped using SSM after this. I'm just using plain old BiLink field now for this purpose (which has it's own set of issues, but let me get past this error - I had a deadline to meet).

**Comment by nilshoerrmann** [comment]
That's just fine - thanks for reporting back.
