### ISSUE TITLE
SubsectionManager timing out in large Section

### ISSUE THREAD

**Issue by jdsimcoe** [symphonists/subsectionmanager#244]
I have a couple large Sections I'm using with SubsectionManager that are having major performance issues on 3.5.1. I'm on Symphony version 2.3.3. Here is a link to the Symphony thread with more details:

http://www.getsymphony.com/discuss/thread/83270/9/#position-163

**Comment by jdsimcoe** [comment]
Adjusted some `php.ini` settings on my webserver at Kirk Strobeck's request:

`max_execution_time = 1000;
max_input_time = 1000; 
memory_limit = 1000M;`

This and Brian Zerangue saw I was that I was missing this file

`/symphony/assets/js/jquery-2.0.3.min.map/`

I executed both of these and the Subsections now work but take around 1 minute to load with content. Any ideas on how to speed things up?

**Comment by nilshoerrmann** [comment]
It's a general problem that cannot be solved easily. The way SSM fetches your subsection entries wasn't created with this large sections in mind.

So actually, this extension needs to be rewritten to solve your issue.

**Comment by jdsimcoe** [comment]
I understand. That being said… how else would I go about solving this issue from a design perspective? Is there another way I could create Teaching Series like this without using SubsectionManager? Any recommendations?

**Comment by nilshoerrmann** [comment]
You could use Selectbox Links but this won't give you the kind of inline UI Subsection Manager provides. The way forward is to create such interface on top of Selectbox Link Field and fully retire Subsection Manager.

**Comment by jdsimcoe** [comment]
Thanks for your help on this… I appreciate the help and response. I have found issues with Select Box link as it selection of multiple elements from a Section. For instance, if I link and select a Tag name, there is no easy way to grab the ID and other associated elements. Same things with Teachings, it just pulls the name and doesn't pull other associated data. Is there something I'm missing or a guide to walkthrough how to properly use SelectBox Link?

**Comment by nilshoerrmann** [comment]
Are you talking about data source output? You'll have to chain data sources to get the data you want – have a look here: http://www.getsymphony.com/learn/concepts/view/data-source-chaining/
