### ISSUE TITLE
Add new button lost after upgrading to Symphony 2.3.4 + Subsectionmanager 3.5

### ISSUE THREAD

**Issue by frenkel** [symphonists/subsectionmanager#247]
I seem to have "lost" the add new button in Subsectionmanager after upgrading both Symphony and Subsectionmanager. The checkbox in the field settings "allow creation of new items" is enabled.

Attached screenshots of Firefox 17 and Chromium. I believe the button is behind the input box: after fiddling with Firebug I can see the button, but can't click it.
![screenshot from 2013-12-16 10 14 46](https://f.cloud.github.com/assets/121169/1753033/d8023036-6632-11e3-9fd0-1f4b28a9d494.png)
![screenshot from 2013-12-16 10 15 14](https://f.cloud.github.com/assets/121169/1753034/d803a13c-6632-11e3-8c36-d39b01c66465.png)

**Comment by nilshoerrmann** [comment]
Thanks for the report. 
Does that still happen after clearing your browser cache?

**Comment by frenkel** [comment]
Sadly yes. I've also tested the subsectionmanager in the sidebar or main content: no difference :(

**Comment by frenkel** [comment]
Which browser are you using to develop this extension? Maybe I can compare the supposed look with my "troubled" version.

**Comment by frenkel** [comment]
I've fixed it for now by using this patch:

```
diff --git a/extensions/subsectionmanager/assets/subsectionmanager.publish.css b/extensions/subsectionmanager/assets/subsectionmanager.publish.css
index 049b6a6..d0beb37 100644
--- a/extensions/subsectionmanager/assets/subsectionmanager.publish.css
+++ b/extensions/subsectionmanager/assets/subsectionmanager.publish.css
@@ -48,6 +48,7 @@

 .field-subsectionmanager .constructable + .browser {
        margin-top: -30px;
+       margin-right: 80px;
 }

 .field-subsectionmanager .browser.opened {

```
