### ISSUE TITLE
Add item iframe is too small, misses scrollbar and add button

### ISSUE THREAD

**Issue by frenkel** [symphonists/subsectionmanager#249]
After fixing the add button, it seems the iframe that appears after clicking on the button is to small. Attached you can see only one row is visible (while there should be two and a create button).
![screenshot from 2013-12-23 14 50 54](https://f.cloud.github.com/assets/121169/1800960/68b29dd6-6bd9-11e3-9151-4203b3f9e79f.png)

After setting the iframe height to 250px instead of 50px, all input fields appear, but the add button is still missing:
![screenshot from 2013-12-23 14 53 08](https://f.cloud.github.com/assets/121169/1800964/94fc2628-6bd9-11e3-82c7-b5fe41a42af9.png)

Anybody know what changed between version 2 and versions 3.5 that causes these problems?

**Comment by nilshoerrmann** [comment]
A few questions:
- Which operating system and browser are you using?
- Have you made sure that all your assets are up-to-date?

**Comment by frenkel** [comment]
Linux with Firefox 17 and latest Chromium.
Everything is directly taken from your master.

-----Oorspronkelijk bericht-----
Van: Nils Hörrmann
Verzonden: 23-12-2013 21:07
Aan: hananils/subsectionmanager
CC: Frank Groeneveld
Onderwerp: Re: [subsectionmanager] Add item iframe is too small, missesscrollbar and add button (#249)

A few questions:
 Which operating system and browser are you using?
 Have you made sure that all your assets are up-to-date?

**Comment by frenkel** [comment]
See my pull-request :)
