### ISSUE TITLE
File Upload CSS

### ISSUE THREAD

**Issue by brendo** [symphonists/subsectionmanager#25]
Seems to be a weird issue in which the file fields color is set to white, which makes it impossible to see if a file has been selected by the extension.

```
body.subsection form input[type="file"] {
    color: #fff;
}
```

Removing the above declaration fixes the problem.

FF 3.6.3 on MacOSX

**Comment by brendo** [comment]
Ah hah, this is the difference between Firefox and Safari's form controls it would seem.

**Comment by doug-stewart** [comment]
Or, Firefox and Safari, Chrome and IE as well. At least I'm pretty sure IE behaves in this instance... I know Chrome and Safari both do.

**Comment by nilshoerrmann** [comment]
Related discussion: http://github.com/nilshoerrmann/subsectionmanager/issues#issue/29
