### ISSUE TITLE
Fatal Error when attempting to update datasource

### ISSUE THREAD

**Issue by wjn** [symphonists/subsectionmanager#254]
When trying to access a datasource for a section utilizing the SSM (v 3.5.1) this error occurs and the datasource cannot be edited.

**Fatal error: Call to a member function fetchFields() on a non-object in .../extensions/subsectionmanager/fields/field.subsectionmanager.php on line 843**

```
    841 // Fetch subsection fields
    842 $section = SectionManager::fetch($this->get('subsection_id'));
    843 $fields = $section->fetchFields();
```

---

I'm running:
- Symphony 2.3.4
- Subsection Manager 3.5.1

**Comment by wjn** [comment]
Upgraded to Symphony 2.3.6 and the problem persists.

**Comment by wjn** [comment]
```
843 $fields = $section->fetchFields();
```

fetchFields() is not a static method and $section has not been instantiated as an object of Section from what I can tell.

**Comment by wjn** [comment]
Within SectionManager the method `fetch()` looks to see if `$_pool` has a section object with the id of `$section_id`. If it find an object it returns it.

```
128     if($returnSingle && isset(self::$_pool[$section_id])){
129         return self::$_pool[$section_id];
130     }
```

However, `$_pool` does not appear to have been set at this point.

**Comment by brendo** [comment]
Has the section that this SSM field was associated too been removed?

**Comment by wjn** [comment]
I don't believe it has; however, there have been many months since the release of the project in which this issue is occurring that I cannot be sure. The challenge at hand is trying to update the datasources but I am being locked out of all datasource editing for all sections in which an SSM field is in play. That common SSM thread is what makes me believe that it's not the case that the field has been removed.

**Comment by wjn** [comment]
Brendo, you were right on the money. Apparently a field had been removed some time ago and that was causing the break. Not a bug with SSM, and thank you for your help.

Incidentally, `$fields` returns a boolean value of `false` when there is a missing field (i.e., one that has been deleted. Also, as you'd know,  `$this->get('subsection_id')` returns the `subsection_id` in the `tbl_fields_subsectionmanager` that can then be tracked to the `field_id` in the `tbl_fields` table.
