### ISSUE TITLE
Upgrading from 1.2 to 3.5.1 gives mysql error[1146]

### ISSUE THREAD

**Issue by moretaste** [symphonists/subsectionmanager#256]
Upgrading from 1.2 to 3.5.1 results in 

```
MySQL Error (1146): Table 'xxx.sym_fields_subsectiontabs' doesn't exist in query: 
SHOW COLUMNS FROM `sym_fields_subsectiontabs` 
LIKE 'allow_dynamic_tabs'
```

Symphony update from 2.2.5 to 2.3.6

**Comment by moretaste** [comment]
Line 368 says `if(version_compare($previousVersion, '1.1', '<')) {` but if I change that into 1.3 I got a new error 

```
MySQL Error (1054): Unknown column 'allow_multiple_selection' in 'sym_fields_subsectionmanager' in query: 
ALTER TABLE `sym_fields_subsectionmanager` 
CHANGE COLUMN `allow_multiple_selection` `allow_multiple` tinyint(1) default '1'
```

**Comment by moretaste** [comment]
Next try comment out from line 371 (// Rename allow multiple column) ends in the initial error

**Comment by nilshoerrmann** [comment]
Does it work when you comment this out?
https://github.com/hananils/subsectionmanager/blob/master/extension.driver.php#L437-L441

**Comment by moretaste** [comment]
Thanks Nils those lines with lines 371-375 did the trick
