### ISSUE TITLE
Will there be an update for Symphony 2.4?

### ISSUE THREAD

**Issue by jurajkapsz** [symphonists/subsectionmanager#257]

**Comment by nilshoerrmann** [comment]
Very unlikely – at least this is nothing we'll be working on actively.

**Comment by jurajkapsz** [comment]
Looks like the core works well (though I am not aware of the whole background at all), I encountered only some minor issues with UI styles, and when creating a new item through SSM (looks as only in-JS issue).

Anyway, I see the point. While it would be definitely fair and worth to cooperate on this, I won't have the time at least throughout the summer. This is one of the nicest ext. Symphony has.

**Comment by nilshoerrmann** [comment]
Instead of updating SSM, it'll make more sense to create a script based on Selectize and the core duplicators that enhances SBL fields. This will make updating much easier in the long term.

But I don't think that we'll start working on this without the support of other users/devs.

**Comment by jurajkapsz** [comment]
> it'll make more sense to create a script based on Selectize and the core duplicators that enhances SBL fields. This will make updating much easier in the long term.

This actually I also have in mind. These things just fit together.

**Comment by jurajkapsz** [comment]
Solved by Association suite. Thanks!
