### ISSUE TITLE
Opening an existing item doesn't close the stage of "Create new"

### ISSUE THREAD

**Issue by johannahoerrmann** [symphonists/subsectionmanager#26]
I click "Create new", the stage opens, I click an existing item above it, this item's stage opens but the "Create new" remains open as well. Clicking the either the new or existing item's draggable top closes both stages and both items remain in the list. Clicking the new item opens the stage (without any fields) and closes it almost completely again right away. I can delete this new item without any problems though.

(I'm sending you some snaps via mail)

**Comment by nilshoerrmann** [comment]
http://github.com/nilshoerrmann/subsectionmanager/commit/baf4bb13e2c8da91b459f7b82b1c12de9f25830a
