### ISSUE TITLE
Conflict with CacheLite

### ISSUE THREAD

**Issue by makenosound** [symphonists/subsectionmanager#27]
Nils—

I've started looking into what's causing [the conflict between CacheLite and the Subsection Manager](http://symphony-cms.com/discuss/thread/41122/4/#position-71), and I've narrowed it down to line 63 of `extension.driver.php`:

```
$callback = Administration::instance()->getPageCallback();
```

Changing this to...

```
$callback = $this->_Parent->getPageCallback();
```

...fixes the conflict, though I'm not sure why the conflict exists in the first place. Note that the error only happens on the `/system/preferences/` page and CacheLite isn't doing anything there apart from appending/saving preferences.

Thoughts?

**Comment by nilshoerrmann** [comment]
This is a problem we should discuss with Alistair. I've no idea why this is happening. But changing the code as you said would do no harm to this extension so we should use it as a fix.

**Comment by makenosound** [comment]
Yup, just had a chat with Alistair. He's a little stumped too:

> Sounds to me like Subsection is calling the function before the page as been resolved perhaps and that is messing it up.
> 
> Must be something quirky about calling Administration::instance() vs. $this->_Parent

**Comment by nilshoerrmann** [comment]
I added the fix here: http://github.com/nilshoerrmann/subsectionmanager/commit/d8002f58a1b7be3ee52d2c1e8ec102b3de4ec024

**Comment by brendo** [comment]
We need to find out if this issue still exists. `$this->_Parent` is gone in 2.3, so the 'solution' won't work moving forward.

**Comment by designermonkey** [comment]
Certainly does need re-addressing, I have just fallen foul of this issue (#184)
