### ISSUE TITLE
"Create new" button is active while creating a new entry

### ISSUE THREAD

**Issue by nickdunn** [symphonists/subsectionmanager#28]
I've not verified this myself, but this report is from a colleague.

When uploading large files over a slow connection this is more noticable. Click "Create new" to open the form. Click "Create new" again and it opens another form. Upload a file in the first, and both disappear once complete. My colleague was trying to upload multiple (large) images simultaneously with odd results.

I think the Create New button should only be active once. If the create form is open, it shouldn't be clickable.

**Comment by nilshoerrmann** [comment]
Interesting: It should not be possible to open more than one create form at once. There seems to be a deeper issue with the opening and closing actions of the different drawers as they seem to behave inconsistent in many ways. I will check this.

**Comment by nilshoerrmann** [comment]
http://github.com/nilshoerrmann/subsectionmanager/commit/52ea6e9557ceacb940f3316a9a426532a27f2ea2
