### ISSUE TITLE
Unique Upload Field text invisible inside of Subsection Manager

### ISSUE THREAD

**Issue by doug-stewart** [symphonists/subsectionmanager#29]
When using the Subsection Manager field with a Unique Upload Field, after selecting an image in the file browser the field remains visually empty but upon saving an image is uploaded.

No javascript errors are observable during this issue.

Latest versions of Draggable, Stage, Subsection Manager and the Unique Upload Field. Other fields in use are the Text Box field. Used on Symphony 2.0.8RC2.

If you'd like, send me a message and I can send you a login for the respective page.

**Comment by nilshoerrmann** [comment]
I think this behaviour is Firefox specific and related to the usage of an upload field inside an iframe. Not sure how to fix this but I'll will investigate this case. I'll mail you if I need more information. You will not be in London for the meet-up in June by any chance?

**Comment by doug-stewart** [comment]
I wish I could be, but no I won't.

It might have something to do with this, but I doubt it. It's just a spelling error, but you never know:

```
Warning: Expected color but found 'transpareant'.  Expected end of value but found 'transpareant'.  Error in parsing value for 'border'.  Declaration dropped.
Source File: http://alanbetts.com/extensions/subsectionmanager/assets/symphony.subsection.css Line: 27
```

**Comment by nilshoerrmann** [comment]
Does correcting this typo change anything in the behaviour?

**Comment by doug-stewart** [comment]
You think I'd have been clever enough to realize I could edit the file on my own site myself... **(gasp!)**

No, it didn't fix it. Would have been too simple I guess.

**Comment by nilshoerrmann** [comment]
;)

**Comment by nickdunn** [comment]
This is the culprit:

```
body.subsection form input[type="file"] {
    color: #fff;
}
```

Firefox honours this and sets the text colour to white, making it invisible against the white background of the input field.

**Comment by doug-stewart** [comment]
I tried using the `-moz-appearance` property to disable Firefox's default styles but it didn't seem to make any difference by setting it to none.

The only solution I could find was to use javascript to make a dummy upload field that populates the real one. The real one is then hidden from view. I guess in this situation that would be acceptable as the entire field runs on javascript anyway.

**Comment by doug-stewart** [comment]
Oh, I also tried setting `border` and `outline` to none, but the issue is even if I set a background I can't get rid of that stupid border around the input box.

**Comment by nickdunn** [comment]
Maybe I'm missing the point — can't that line of CSS simply be removed?

**Comment by nilshoerrmann** [comment]
http://github.com/nilshoerrmann/subsectionmanager/issues#issue/25

**Comment by nickdunn** [comment]
Bah who uses that Safari piece of shit anyway :-P

**Comment by nilshoerrmann** [comment]
Hey! I like it :)

**Comment by doug-stewart** [comment]
So do I and it works fine in Chrome as well as Safari. I'm also reasonably certain that it'd be fine in IE as well.

You know, you could always use JS to target Firefox and apply a class to override the font color?
