### ISSUE TITLE
File paths don't honor Symphony being installed in a subdirectory

### ISSUE THREAD

**Issue by michael-e** [symphonists/subsectionmanager#3]
If you have installed Symphony in a subdirectory (.i.e. not in the root of your website), none of the file paths will work - not even the one which is displayed in "edit mode". Those links are root links, so they must include the subdirectory (resp. the full URL).

**Comment by nilshoerrmann** [comment]
I'm not sure I know which links you are talking about?

**Comment by michael-e** [comment]
Case 1: installed in the root. Drag-and-drop links are wrong (see bug #2), but if you open the inline editor, you will see a correct link to the file.

Case 2: installed in a subdirectory. Not even the link in the inline editor will work.

**Comment by nilshoerrmann** [comment]
I understand case 1 but what's "the link in the inline editor". Sorry, ich stehe da gerade auf dem Schlauch ...

**Comment by michael-e** [comment]
Check your email!

**Comment by michael-e** [comment]
Please close this bug. I have been confused by the behavior of the standard file upload field. It will display a "shortened" link, starting with "/workspace". Nevertheless the actual link will work.

**Comment by nilshoerrmann** [comment]
Case closed :)
