### ISSUE TITLE
New entries not attached upon save

### ISSUE THREAD

**Issue by pointybeard** [symphonists/subsectionmanager#31]
I have a feeling this is in some way related to http://github.com/nilshoerrmann/subsectionmanager/issues#issue/30

It would appear that a new entry created in a Subsection Manager field, of a section with no entries, the entry does not stay attached to the entry when saved. (guh, what a mouthful)

To reproduce:
1. Create a basic setup of one section with a subsection field pointing to another section. For this example I will just Articles and Categories.
2. Create an Article, adding a new category entry via the subsection manager field
3. Save the article

Expected: The new category has been created and is attached to the article
Actual Result: The new category entry is created, but not attached to the article

Some things I have observed. 
1. This appears to only happen when there are no entries in the, for example, "category" section. If I manually create a category first, and follow the same steps above, the bug is not reproduced.
2. The POST data when saving when there are no existing categories, and the POST data after saving when there are existing categories differs.

Here is the POST data when there are no existing categories:

```
array
  'MAX_FILE_SIZE' => string '5242880' (length=7)
  'fields' => 
    array
      'title' => string 'Banana' (length=12)
      'sort_order' => 
        array
          163 => string '18,0' (length=4)
      'subsection_id' => 
        array
          163 => string '34' (length=2)
  'action' => 
    array
      'save' => string 'Create Entry' (length=12)
```

and here is the POST data when there are existing categories (not this is not attaching an existing. A new category is still created in the Subsection Manager field as in the first example):

```
array
  'MAX_FILE_SIZE' => string '5242880' (length=7)
  'fields' => 
    array
      'title' => string 'Banana' (length=12)
      'categories' => 
        array
          0 => string '18' (length=2)
      'sort_order' => 
        array
          163 => string '' (length=0)
      'subsection_id' => 
        array
          163 => string '34' (length=2)
  'action' => 
    array
      'save' => string 'Create Entry' (length=12)
```

Notice the missing 'categories' item in the POST data of the first example. 

I am hopeful that helps debug the problem.

**Comment by nilshoerrmann** [comment]
Alistair, thanks for reporting.

**Comment by nilshoerrmann** [comment]
This should hopefully been fixed now: http://github.com/nilshoerrmann/stage/commit/ff889834673218f9120bdad242f439036097f218
