### ISSUE TITLE
CSS Issue - CKEditor not properly displayed in subsection

### ISSUE THREAD

**Issue by icek** [symphonists/subsectionmanager#32]
rule `body.subsection form label span` affects CKEditor. Should be changed to eg. `body.subsection form label > span`.

**Comment by nilshoerrmann** [comment]
Thanks icek.

**Comment by nilshoerrmann** [comment]
http://github.com/nilshoerrmann/subsectionmanager/commit/2b0de301e70864f66f848caa02fd2148eb419b93
