### ISSUE TITLE
Tag list in section preferences not working in S2.1.0 

### ISSUE THREAD

**Issue by icek** [symphonists/subsectionmanager#33]
In section preferences `Custom item caption` tag list is no longer clickable after updating to S2.1.0

**Comment by nilshoerrmann** [comment]
Yes, I noticed that as well. Something seems to have changed in the core JavaScript.

**Comment by nilshoerrmann** [comment]
Just checked it again - and it is working now again. Maybe an caching issue?

**Comment by icek** [comment]
if you are using only one subsection it's working or if this is first of all created subsections. This is becuse you are always generating taglists for all sections and then you are showing via js only one: `subsectionmanager.find('ul.inline').hide().filter('.section' + id).show();` in `settings.subsectionmanager.js`. The code for finding input in core js is: `var input = list.prev().find('input')[0];`, so when there are any hidden it doesn't find anything.

Proper tag list should be filterer in php not by js. Quick workaround in js is to replace mentioned above line: `subsectionmanager.find('ul.inline').hide().filter('.section' + id).show();` to `subsectionmanager.find('ul.inline').show().filter(':not(.section' + id+')').remove();`

**Comment by icek** [comment]
ok, after more investigations I know why you are filtering that way.
My new solution is to change: `subsectionmanager.find('ul.inline').hide().filter('.section' + id).show()` to: `subsectionmanager.find('ul.inline').hide().filter('.section' + id).show().insertBefore(subsectionmanager.find('ul.inline:first'));`

Now section related taglist is moved just after label/input, so `list.prev().find('input')[0];` works properly. I didn't test this with only one subsection!

**Comment by nilshoerrmann** [comment]
Ah, I see. Thanks for investigating. I'll have to revise the whole preference pane of the Subsection Manager because I still have to implement the Stage settings. So maybe it's time to rethinks the whole way the preferences for subsection work.

**Comment by nilshoerrmann** [comment]
This has been fixed in my working copy which I will push to GitHub as soon as the preferences are fully functional.
