### ISSUE TITLE
Every Publish Page opened in an iframe gets Subsectionmanager JS

### ISSUE THREAD

**Issue by klaftertief** [symphonists/subsectionmanager#34]
I'm loading Publish Pages into an iframe in a separate extension and the JavaScript from `symphony.subsection.js` gets fired and breaks/modifies the original layout. The logic to either load the Subsectionmanager assets or to call the JS modifications should be stricter.

**Comment by nilshoerrmann** [comment]
Any ideas how to distinguish between the differrent iframe implementations?

**Comment by klaftertief** [comment]
Because page doesn't know that it's going to be loaded from an iframe the logic has to go into the page with the iframe. You could access and modify the _iframed_ page dynamically from its parent page with something like `jQuery('iframe[name=subsection-foo]').contents().yourModifyFunction();`. Haven't tried it, but I would be my first guess.

**Comment by klaftertief** [comment]
Oops, I accidentally closed the issue.

**Comment by klaftertief** [comment]
http://github.com/klaftertief/subsectionmanager/commit/fac2064ed9dee4a8a89ccf0e2a0c1363aa4b1f4a seems to do the trick. Without raising claim for brilliancy.

Do you want a pull request?

**Comment by nilshoerrmann** [comment]
Yes, please.

**Comment by nilshoerrmann** [comment]
Hm, Jonas, I just pulled your changes. This seems to cause some issues with the height calculation of the iframe. I guess this is some sort of timing problem: the changes to the iframe content have not been applied when the script tries to calculate its height.

Maybe it would be better to handle the layout changes using a delegate on the PHP side?

**Comment by nilshoerrmann** [comment]
Never mind - I had some cashing trouble.

I changed the variable names a bit to match the naming scheme I currently use. Maybe there should be an agreement in the Symphony community whether to use or not to use the dollar notation for "jqueryfied" objects. I can live with both concepts but will stick with my current style at the moment for consistency reasons.
