### ISSUE TITLE
New Items Not Added Properly

### ISSUE THREAD

**Issue by markgoodyear** [symphonists/subsectionmanager#35]
When I add an item from an upload, Subsection Manager doesn't save that and add it to the selection. Instead, once I have added the item for upload, I have to save the Subsection Manager part, then save the actual page I am editing. Then I need go back into the Subsection Manager, add the newly uploaded file to the selection, then re-save the main page.

This is using a fresh install of Symphony 2.1 and the latest Subsection Manager, Stage and Draggable.

**Comment by nilshoerrmann** [comment]
Thanks for this report. This seems to be an endless bug popping up now and then. 
- Which browser are you using?
- What's your operating system?
- Can you reproduce this bug in different browsers?
- Are there any messages in the JavaScript console?

**Comment by markgoodyear** [comment]
It happens in Chrome, Firefox and Safari on Mac OSX Leopard 10.5.8.

I have checked with the Firebug JavaScript console, and there are no errors or warnings.

**Comment by nilshoerrmann** [comment]
Okay, I'll check that soon.

**Comment by nilshoerrmann** [comment]
I cannot reproduce this behaviour. It's working for me with newly created entries as well as with already existing ones. 

Are you using the core upload field?

**Comment by markgoodyear** [comment]
Yeah, I am using the core upload field. Would you be able to zip your Subsection Manager folder and upload it somewhere? I can then try that to see if that makes any difference.

**Comment by nilshoerrmann** [comment]
Of course. Could you send me an [email](http://nilshoerrmann.de/impressum/), please?

**Comment by icek** [comment]
I can confirm that 2 step saving. First for entry creation, second for saving subsection's selection.

**Comment by nilshoerrmann** [comment]
I'm still not able to reproduce this behaviour. So you are doing the following:
- You create a new entry in your parent section.
- You create a new item in your subsection by selecting a file for upload and clicking `Create Entry`. The item will then be created and added to the list of selected items
- You click `Create Entry` in your parent section to save your new entry.
- The page reloads and nothing is selected in the subsection field?

Is that what's happening?

**Comment by icek** [comment]
Yes

**Comment by nilshoerrmann** [comment]
I just double checked it in my install and it's saving correctly. 
- Which fields do you have in your parent and your subsection?
- Which is the position of your subsection field (first field, last field in the section)?

**Comment by nilshoerrmann** [comment]
It this happening on beta2 or RC1?

**Comment by nilshoerrmann** [comment]
And another question: What are your field settings?

**Comment by nilshoerrmann** [comment]
Which operating system are you working on? Mac, PC, Linux?

**Comment by icek** [comment]
I have 6 sections with different field and this happend in all of them. Now I created new with: Text Field and Subsection Manager with: Text Field
- Symphony 2.1,
- Subsection Manager 1.0RC1,
- Field settings: Every option checked except for Allow dropping items, Show image thumbnails and Field required.
- OS: Mac OS-X Snow Leopard
- Browser: Firefox, Chrome, Safari

**Comment by nilshoerrmann** [comment]
Have you been cloning the three Git repositories or are you using the ZIP download from the forum?

**Comment by icek** [comment]
I'm always downloading zip from github

**Comment by nilshoerrmann** [comment]
Okay, would you be so kind and try the ZIP file I uploaded in the forum to see if it's a general problem or if something is messed up in the repositories? Thanks!

http://symphony-cms.com/discuss/thread/41122/10/#position-182

The package contains everything you need (Subsection Manager, Stage and Draggable).

**Comment by icek** [comment]
That link is broken (forbidden)

**Comment by nilshoerrmann** [comment]
Sorry, I copied the wrong link from the forum. I updated my post above. (Sorry, it's still quite early here ...)

**Comment by icek** [comment]
Now after creation of item in subsection and saving it dissapers. When I click in search field I see only previously added items. After saving section item is on list again.

**Comment by nilshoerrmann** [comment]
Are you testing locally or on a public server?

**Comment by michael-e** [comment]
> Now after creation of item in subsection and saving it dissapers. When I click in search field I see only previously added items. After saving section item is on list again.

Same here, using Safari 5.0.1 on OS X 10.6.4. 

The newly created item will appear in the list after page reload.

**Comment by nilshoerrmann** [comment]
Have you all been updating using the Git repositories? I don't understand why you are all experiencing this issues and why it's working for me.

Maybe something is missing in one of the repositories or in the database? The ZIP archive in the forum is an exact copy of my development install.

**Comment by nilshoerrmann** [comment]
I've been mailing with icek and the issue seems to be (partly) related to a regular expression which tries to fetch the new item id.

Is it possible that all of you who are experiencing this issue have been either using a subsection with a number in its name or that you have your test install in a folder structure containing a number?

**Comment by nilshoerrmann** [comment]
Please have a look here: http://github.com/nilshoerrmann/subsectionmanager/commit/55499053915014d6fedb7202acde46526856a117

**Comment by nilshoerrmann** [comment]
And this is the final needed fix:
http://github.com/nilshoerrmann/stage/commit/d5876ceed817373017b82eeb0e3c79b1d16b55d3

Many thanks for icek who patiently helped tracking down this persistent bug.

**Comment by markgoodyear** [comment]
To confirm for anyone having this problem, it is now working properly. Great work Nils!
