### ISSUE TITLE
Stage preferences table not created durring update

### ISSUE THREAD

**Issue by icek** [symphonists/subsectionmanager#39]
After updating to RC1 i get following error:

> Symphony Fatal Database Error
> Table 'vimuseo.sym_fields_stage' doesn't exist

**Comment by icek** [comment]
I've noticed that you changed row name from `allow_multiple_selection` to `allow_multiple` in `sym_fields_subsectionmanager`

**Comment by nilshoerrmann** [comment]
> I've noticed that you changed row name from allow_multiple_selection to allow_multiple in sym_fields_subsectionmanager

Please have a look here: http://symphony-cms.com/discuss/thread/41122/10/#position-181

**Comment by nilshoerrmann** [comment]
Concerning the fatal error, this is the missing table: 

```
CREATE TABLE IF NOT EXISTS `tbl_fields_stage` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `field_id` int(11) unsigned NOT NULL default '0',
  `constructable` smallint(1) default '0',
  `destructable` smallint(1) default '0',
  `draggable` smallint(1) default '0',
  `droppable` smallint(1) default '0',
  `searchable` smallint(1) default '0',
  PRIMARY KEY  (`id`)
) TYPE=MyISAM;
```

Where `tbl_` is your current table prefix.
