### ISSUE TITLE
Creating an item won't work immediately after deleting an item

### ISSUE THREAD

**Issue by michael-e** [symphonists/subsectionmanager#4]
Steps to reproduce (tested in latest Safari and Firefox on mac OS X):
- delete an item
- do not save your entry
- click on "create new"
- the GUI is broken

You will see the text "New item - Please fill out the form below", but there is no form below nor elsewhere.

**Comment by nilshoerrmann** [comment]
[Fixed here](http://github.com/nilshoerrmann/subsectionmanager/commit/774964ecaf2f9b123cbab07cc443994e800cae90).
