### ISSUE TITLE
Error when creating new section

### ISSUE THREAD

**Issue by icek** [symphonists/subsectionmanager#40]
Symphony Warning appears when saving new section with subsection manager included.

```
explode() expects parameter 2 to be string, array given
/Users/grzegorz/Sites/vimuseo.fi/www-2/extensions/subsectionmanager/fields/field.subsectionmanager.php line 227

222         foreach($field_groups as $group) {
223             if(!is_array($group['fields'])) continue;
224             $fields = array();
225             foreach($group['fields'] as $field){
226                 if($field->get('id') != $this->get('id')) {
227                     $fields[] = array($field->get('id'), (in_array($field->get('id'), explode(',', $this->get('included_fields')))), $field->get('label'));
228                 }
229             }
230             if(is_array($fields) && !empty($fields)) {
231                 $options[] = array('label' => $group['section']->get('id'), 'options' => $fields);
```

**Comment by nilshoerrmann** [comment]
icek, this is related to [your issue here](http://github.com/nilshoerrmann/subsectionmanager/issues#issue/36), I guess. Are you by any chance using a modified Symphony version?

**Comment by nilshoerrmann** [comment]
So - as with the first issue - I cannot reproduce it at the moment.

**Comment by icek** [comment]
Symphony 2.1 without any modifications. I found that warning was thrown when I forgot to fill Caption field.

**Comment by nilshoerrmann** [comment]
>  I found that warning was thrown when I forgot to fill Caption field.

That shouldn't happen. The field should create a default caption (this is what it's actually doing on my install).

**Comment by icek** [comment]
I could not reproduce this anymore. Maybe something was cached...

**Comment by nilshoerrmann** [comment]
Are you talking about the PHP error or the caption problem?

**Comment by icek** [comment]
About PHP error

**Comment by nilshoerrmann** [comment]
Okay, great. Thanks!

**Comment by nilshoerrmann** [comment]
Does the caption issue still exist or did it disappear as well?

**Comment by icek** [comment]
Seemd that this dissapper. Probably that was a cache problem.

**Comment by nilshoerrmann** [comment]
Fine. Thanks for reporting back.
