### ISSUE TITLE
[RC1] Cannot select multiple existing items

### ISSUE THREAD

**Issue by pointybeard** [symphonists/subsectionmanager#41]
Seems that RC1 has introduced a bug where selecting a 2nd item removes the 1st. Could this be related to the new table "stage" and a lack of configuration data after upgrading?

**Comment by nilshoerrmann** [comment]
This is related to a change in the Subsection Manager Field database table ([it's described here](http://symphony-cms.com/discuss/thread/41122/10/#position-181)). The `allow_multiple_selection` column has been renamed to `allow_multiple`.

You will have replace this:

```
`allow_multiple_selection` enum('yes','no') NOT NULL default 'yes',  
`show_preview` enum('yes','no') NOT NULL default 'yes',
```

with that:

```
`allow_multiple` tinyint(1) default '0',  
`show_preview` tinyint(1) default '0',
```

in `tbl_fields_subsectionmanager`.

**Comment by pointybeard** [comment]
Ah, thanks. That fixed it.
