### ISSUE TITLE
Updating to RC1

### ISSUE THREAD

**Issue by pointybeard** [symphonists/subsectionmanager#42]
Couple of problems when updating.

It seems there is a new table, `tbl_fields_stage`, which is created on install, but not update. Throws errors if you try to access a sections publish area with an existing subsection field.

Secondly, there is no submodule mapping for `lib/stage` anymore, and this seems to stuff up the repo. I added it to my fork, and that seemed to fix the problem.

**Comment by nilshoerrmann** [comment]
Alistair, you should have a look at the forum thread :o)

Concerning the submodule. I managed to crash my Stage repository yesterday -- I thought I fixed everything but maybe this is a result of my trouble.

**Comment by pointybeard** [comment]
> Alistair, you should have a look at the forum thread :o)

Ha, I guess I should. ;)
