### ISSUE TITLE
Table 'something.sym_fields_stage' doesn't exist in RC2

### ISSUE THREAD

**Issue by icek** [symphonists/subsectionmanager#43]
Following error appers in clean instalation of Symphony 2.1 + Subsection Manager 1.0RC2 when creating new section:

>    Symphony Fatal Database Error
>    Table 'test.sym_fields_stage' doesn't exist
> 
>    An error occurred while attempting to execute the following query
> - SELECT \* FROM sym_fields_stage WHERE field_id = '' LIMIT 1

**Comment by icek** [comment]
Sorry, it was RC1

**Comment by nilshoerrmann** [comment]
So it's working in RC2, I suppose?

**Comment by icek** [comment]
yes, it's working :)
