### ISSUE TITLE
Unable to select a just created item

### ISSUE THREAD

**Issue by simoneeconomo** [symphonists/subsectionmanager#44]
Here are the steps to reproduce it:
1. Create an entry and save it
2. Click on “Browse”
3. De-select it by clicking on the (x) button
4. Click on “Browse”
5. Try to select the newly created item

You won't be able to select that item as you would expect to. As far as I know, it only happens when you follow the above procedure.

**Comment by nilshoerrmann** [comment]
It seems like the events have not been attached properly to the newly created item's remove button.

**Comment by nilshoerrmann** [comment]
This was a bug in Stage: http://github.com/nilshoerrmann/stage/commit/7c263e2bdcae03a90a5deb293ddedcc721b6ff26
