### ISSUE TITLE
The accordion doesn't work properly

### ISSUE THREAD

**Issue by simoneeconomo** [symphonists/subsectionmanager#45]
Under some unknown circumstances, clicking on a selected entry won't make it expanded. It seems to happen half of the times.

Experienced on: Chromium 5.0.375.125, Firefox 3.6.8. Not able to reproduce that.

**Comment by nilshoerrmann** [comment]
There are two possible reasons:
1. The event handlers have not been attached properly for the new item.
2. The drawer template has been deleted by fault.

Note: There was a change that reordered jQuery selectors for template exclusion. Maybe this is the reason for this issue.

**Comment by nilshoerrmann** [comment]
Simone, could you test the latest changes in the `development` branch and see if this solved the issue by chance. If not, do you have any tips how to reproduce this behaviour?

**Comment by nilshoerrmann** [comment]
I tried it, but currently I'm not able to reproduce this behaviour. (But I know that this has been a problem a while back.)

**Comment by nilshoerrmann** [comment]
There are a couple of Stage updates that hopefully fix this issue.
