### ISSUE TITLE
Deselecting an expanded entry doesn't hide its details

### ISSUE THREAD

**Issue by simoneeconomo** [symphonists/subsectionmanager#47]
Here are the steps to reproduce it:
1. Click on an entry in order to edit it
2. Deselect the entry by clicking on the (x) button

The caption is removed, but the dark box with all the details stays in place, thus allowing you to keep editing the entry.

Experienced on: Chromium 5.0.375.125, Firefox 3.6.8.

**Comment by nilshoerrmann** [comment]
This is related to #45 as well.
