### ISSUE TITLE
Subsection Manager not working on Opera 10.61

### ISSUE THREAD

**Issue by simoneeconomo** [symphonists/subsectionmanager#48]
While using Opera 10.61, I noticed that the Subsection Managet interface is broken. In fact, the white bar (with the search input and the "Create new" button) is not displayed at all.

Opera is the only one with this kind of rendering issue. All other browsers (except IE which hasn't been tested) behaves as expected.

**Comment by nilshoerrmann** [comment]
Beside the fact that there are no rounded corners, Opera 10.10 seems to work just fine for me. Can you confirm that this wasn't some kind of caching issue?

**Comment by simoneeconomo** [comment]
Sorry, forget that. It was my fault!
