### ISSUE TITLE
The suggestions for the tag/category filter don’t work.

### ISSUE THREAD

**Issue by klaftertief** [symphonists/subsectionmanager#49]
The reason are the multiple tag suggestion lists (<ul>) and this change in admin.js.

**Comment by nilshoerrmann** [comment]
Thanks, Jonas.

Note: The category filter lists need to be merged into one list (see changes for the caption suggestions).

**Comment by nilshoerrmann** [comment]
Fixed: http://github.com/nilshoerrmann/subsectionmanager/commit/c469fa737451e08a02a98446a0a31ff5b69e24d9
