### ISSUE TITLE
Error on initial page load

### ISSUE THREAD

**Issue by michael-e** [symphonists/subsectionmanager#5]
If you load an entry edit page containing a Subsection Manager field, you will see the following error in the firebug console:

```
"NetworkError: 404 Not Found - http://me/symphony207/symphony/publish/images/%7b$action%7d/%7b$id%7d/"
```

Even without really understanding the manager class, I am rather sure this error is connected to the `create_new` variable, which is defined in line 378 of field.subsectionmanager.php:

```
$create_new = URL . '/symphony/publish/' . $subsection_handle . '/{$action}/{$id}';
```

The {$action}/{$id} pattern is perfidious, isn't it?

**Comment by nilshoerrmann** [comment]
I never noticed this in my local install. Will check that out.

**Comment by nilshoerrmann** [comment]
I cannot reproduce this on my install. Any further hints?

**Comment by nilshoerrmann** [comment]
I think I found a fix: http://github.com/nilshoerrmann/subsectionmanager/commit/5490552aaeae34b3bdd538fc0c0f7d379629bc1b
