### ISSUE TITLE
The filter by tags doesn’t work. 

### ISSUE THREAD

**Issue by klaftertief** [symphonists/subsectionmanager#50]
If I put a tag/category in the filter field not entries in the Subsection Manager on the publish editor are found.

**Comment by nilshoerrmann** [comment]
Hm, this might be related to the name changes in database.

**Comment by nilshoerrmann** [comment]
[Fixed](http://github.com/nilshoerrmann/subsectionmanager/commit/d43be095308aa3cc60700760bccd7ad1c8c4af34), it was a typo.
