### ISSUE TITLE
The display of the suggestions for the custom caption doesn’t work correctly.

### ISSUE THREAD

**Issue by klaftertief** [symphonists/subsectionmanager#51]
Not all field handles from the selected subsection are shown, and if no handle is shown the display of the input field is broken (too low, bottom outline is cut off).

**Comment by nilshoerrmann** [comment]
Jonas, gibt es ein bestimmtes Schema? Also werden nur bestimmte Felder ausgelassen (bestimmte Typen oder immer die hinteren 10)?

**Comment by klaftertief** [comment]
The reason are multiple handles with the same name. The `rel`-attribute then contains multiple sections, but the show/hide logic only works for a single section.

Changing

```
        subsectionmanager.find('ul.inline li').hide().filter('*[rel=section' + id + ']').show();
```

to 

```
        subsectionmanager.find('ul.inline li').hide().filter('[rel~=section' + id + ']').show();
```

on line 40 on settings.subsectionsmanager.js solves the issue.

**Comment by nilshoerrmann** [comment]
Besten Dank!
(Und Du hast nicht `Comment and Close` geklickt!)

**Comment by nilshoerrmann** [comment]
[Commited](http://github.com/nilshoerrmann/subsectionmanager/commit/7fcfe23b847586f93c074e46c0ec310a958d6d2e).
