### ISSUE TITLE
Dragging an entry over an textarea but dropping it back to the subsection manager adds the image/file link into the textarea.

### ISSUE THREAD

**Issue by klaftertief** [symphonists/subsectionmanager#52]

**Comment by nilshoerrmann** [comment]
Good catch. Not sure why this is happening though. In which browser were you testing?

**Comment by klaftertief** [comment]
Latest Safari, Firefox, Chrome and Opera on OS X :)

**Comment by klaftertief** [comment]
Sorry, I always click "Comment and Close". Annoying.

**Comment by nilshoerrmann** [comment]
No problem :)

**Comment by nilshoerrmann** [comment]
This has been fixed in Draggables and the Subsection Manager itself.
