### ISSUE TITLE
"Seems that filtering by subsection field won't work."

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/subsectionmanager#53]
See icek's email.

**Comment by nilshoerrmann** [comment]
This needs further testing and will be added in version 1.1.

**Comment by BBQbrains** [comment]
When I use a ds output parameter based on a Subsection Manager field to filter its linked section, the chained ds only returns a single result matching the first id in the parameter list. However, if I paste the literal value of the ds output parameter into the chained ds filter field, results are returned for all ids in the list. 

http://symphony-cms.com/discuss/thread/47804/

**Comment by icek** [comment]
as I mailed Nils before, to make it work: copy buildDSRetrivalSQL function from SelectBox Link extension (fields/field.selectbox_link.php) to Setion Manager (fields/field.selectbox_link.php). You don't need to change anything, Just copy&paste.

**Comment by BBQbrains** [comment]
icek,

The current version of Subsection Manager doesn't have the file fields/field.selectbox_link.php. So I copied the function to field.subsectionmanager.php, but that didn't change anything. Were you meaning something different?

**Comment by icek** [comment]
Yes, go to extensions/selectbox_link_field or download this extension from http://github.com/pointybeard/selectbox_link_field (this is what I was thinking when I wrote "SelectBox Link extension"), and there you'll find file field.selectbox_link.php

**Comment by icek** [comment]
from this file: http://github.com/pointybeard/selectbox_link_field/blob/master/fields/field.selectbox_link.php copy lines 399-464 to your field.subsectionmanager.php

**Comment by icek** [comment]
I think that your problem is diffferent from mine. Check this ensemble: http://grzegorz.michlicki.pl/subsection-test-ensemble.zip It shows problem related to this bug.

**Comment by BBQbrains** [comment]
icek,

I figured that was what you meant, and that's what I did. But it didn't change anything in my situation.

I don't know the details of your filtering problem, so they may be completely different issues.

**Comment by icek** [comment]
CCQbranins: check this issue: http://github.com/nilshoerrmann/subsectionmanager/issues/closed#issue/36 maybe this is it?

**Comment by BBQbrains** [comment]
That looks like the same problem, and the solution worked. :)

But I'm guessing the solution is temporary since we're removing an intended behavior rather than fixing it. Should this issue be in the closed list?

**Comment by nilshoerrmann** [comment]
Try using this version and tell me if it's still working for you:

```
    public function buildDSRetrivalSQL($data, &$joins, &$where, $andOperation=false) {

        // Current field id
        $field_id = $this->get('id');

        // Filters connected with AND
        if($andOperation) {
            foreach($data as $key => $value) {
                $joins .= " LEFT JOIN `tbl_entries_data_$field_id` AS `t$field_id$key` ON (`e`.`id` = `t$field_id$key`.entry_id) ";
                $where .= " AND `t$field_id$key`.relation_id = '$value' ";
            }
        }

        // Filters connected with OR
        else {
            $joins .= " LEFT JOIN `tbl_entries_data_$field_id` AS `t$field_id` ON (`e`.`id` = `t$field_id`.entry_id) ";
            $where .= " AND `t$field_id`.relation_id IN ('" . @implode("', '", $data) . "') ";
        }

        return true;
    }   
```

**Comment by icek** [comment]
finally I've found time to test this. It's working. Thanks Nils!

@BBQbrains: Can you check this: http://github.com/nilshoerrmann/subsectionmanager/issues/issue/36/#comment_413321

**Comment by ahwayakchih** [comment]
This feature request is closed, but it seems that code was never commited. Are there any plans to update it?

I have added code posted above and it works well so far :).
