### ISSUE TITLE
CSS Issue

### ISSUE THREAD

**Issue by icek** [symphonists/subsectionmanager#56]
Checkbox field in subsection not displayed correctly (at least in FF Mac).
Checkbox is centered, Label starts below at left.

**Comment by icek** [comment]
I've added rule to `symphony.subsection.css`:

> body.subsection fieldset input[type="checkbox"] {  
>   width: auto;  
> }  

an now it is perfect

**Comment by nilshoerrmann** [comment]
Fixed: http://github.com/nilshoerrmann/subsectionmanager/commit/df42ddecb5e3dd54a8000cb06e8406514d64df39
