### ISSUE TITLE
Flickering of textarea drop overlay

### ISSUE THREAD

**Issue by klaftertief** [symphonists/subsectionmanager#57]
It's just a small flaw. When you drag an item from the Subsection Manger over a textarea the transparent black dropper element might start flickering. This happens, when you move the cursor fast enough that it hovers the actual drag helper element.

**Comment by nilshoerrmann** [comment]
I noticed this a while back, too. But how should this issue be solved?

**Comment by nilshoerrmann** [comment]
This should be fixed together with [other drag and drop improvements](http://github.com/nilshoerrmann/subsectionmanager/issues#issue/21) in version 1.1.

**Comment by nilshoerrmann** [comment]
The drag implementation will change in the next version of this extension and this issue seems to be fixed.
