### ISSUE TITLE
Dragging a file into a text field should not prepend the server address

### ISSUE THREAD

**Issue by tonyarnold** [symphonists/subsectionmanager#58]
Presently when you drag a file from SSM into a text field, it creates the link to the file using the full server absolute URI. I think this should be changed a server relative URL, ie:

`/workspace/resources/my-great-file.jpg`

Otherwise it makes moving from test/dev to production a heck of a lot harder.

(Duplicated from http://symphony-cms.com/download/extensions/issues/view/41121/10/)

**Comment by nickdunn** [comment]
I second this, I had to write a script to edit a load of tables recently to remove these.

**Comment by nilshoerrmann** [comment]
Removing `URL` form [line 201](http://github.com/nilshoerrmann/subsectionmanager/blob/release/lib/class.subsectionmanager.php#L201) of `lib/class.subsectionmanager.php` should fix your issue.

But the new links won't work on installs in subfolders. So it's fixing one issue and creating a new one. Ideas?

**Comment by tonyarnold** [comment]
Thanks, Nils. 

It's a little extra work, but what about performing a regex on the `URL` constant to just grab everything from the first slash? On installs that don't use subfolders, it'll be nil - but on installs that do you'll get the same result as you would have before this change.

**Comment by nilshoerrmann** [comment]
That doesn't help when the development and the live installs are in different folders. Maybe the best idea would be to include some kind of upgrade script.

**Comment by tonyarnold** [comment]
I'll put something forward to the Core WG about including the server relative path in an accessible way in 2.2, and work on a patch. I don't think extensions should have to handle the upgrade of URLs themselves.

But for now, yes - you're probably stuck with an upgrade script :(

**Comment by nilshoerrmann** [comment]
@Nick: Would you mind sharing the script you created for this purpose?

**Comment by nilshoerrmann** [comment]
This will be fixed in version 1.1 together with other drag-related issues.

**Comment by nickdunn** [comment]
I no longer have it, but it was fairly simple:
- query tbl_fields for Textarea fields
- iterate over the field IDs
- update content from the table for each of these fields matching a REGEXP condition

**Comment by nilshoerrmann** [comment]
The next version of Subsection Manager will replace predefined formats with custom drop captions that can be defined in the field preferences. So it will be possible to either add or remove `{$root}` from the drop text.
