### ISSUE TITLE
Firebug warnings when using search

### ISSUE THREAD

**Issue by michael-e** [symphonists/subsectionmanager#6]
Typing something into the search field, you will find warnings in the firebug console:

> Die 'charCode'-Eigenschaft eines keyup-Ereignisses sollte nicht verwendet werden. Der Wert ist bedeutungslos.

(German version of firebug...)

There is one warning for each character you type.

**Comment by nilshoerrmann** [comment]
Well, yes. That's a relict of the Mediathek field ... I'm not sure if the Firebug warning is correct though.

**Comment by nilshoerrmann** [comment]
I misunderstood your report and thought you were talking about the section settings. I cannot reproduce this issue using Firefox 3.6. 

Do you use any other JavaScript based extension that might hook into the key events?

**Comment by michael-e** [comment]
I tried a rather clean install, using only these extensions:
- Debug DevKit
- Export Ensemble
- Field: Select Box Link
- JIT Image Manipulation
- Maintenance Mode
- Profile Devkit
- Subsection Manager
- Text Formatter: Markdown

Still I get one error for every letter I type in the search field.

**Comment by nilshoerrmann** [comment]
Hm, I checked the source of all related Subsection Manager JavaScript files and I couldn't find anything that would cause this error.

**Comment by michael-e** [comment]
It's gone if I comment out line 167-169 in symphony-stage.js:

```
if(settings.searchable) {
    object.find('div.queue .browser').bind('click keyup', object.stage.search);
}
```

(Of course this breaks search.)

**Comment by nilshoerrmann** [comment]
This might be jQuery related. There was an update between Symphony 2.0.7 and 2.0.8RC1? Which version are you using?

**Comment by michael-e** [comment]
I experience this on 2.0.7 and 2.0.8 RC1 alike. But I agree that it might be related to jQuery...

**Comment by nilshoerrmann** [comment]
Just to fully test this issue could you just remove the `keyup` from the snippet you posted above and see if this stops the error messages from popping up?

**Comment by michael-e** [comment]
Confirmed. Error stops, search breaks.

**Comment by nilshoerrmann** [comment]
So it's definitely a jQuery bug then. As it's a warning nothing is broken. Case closed for now.
