### ISSUE TITLE
Allow selectbox_link field in Caption

### ISSUE THREAD

**Issue by tachyondecay** [symphonists/subsectionmanager#60]
Currently selectbox_link fields do not work with the Subsection Manager's Caption, because this field returns only a relation_id instead of a value.  So when a selectbox_link field is added to the Caption, nothing is output.  It would be great if this could change so the caption includes whatever value is displayed in the selectbox_link field when editing the entry.

**Comment by nilshoerrmann** [comment]
The next version of this field will support relation fields like select box links or reference links by calling `prepareTableValue()` for these field types.
