### ISSUE TITLE
Do not close the item editing form if it loses focus

### ISSUE THREAD

**Issue by tachyondecay** [symphonists/subsectionmanager#63]
If I am editing an item within the subsection manager, the form closes if it loses focus (i.e., if you click elsewhere on the page).  This is frustrating because the form does not save its changes, and when you click on the item again to resume editing, it loads the item fresh.  I've lost a lot of changes that way.

There are two possible solutions; I'm not sure which one is better.  First, don't close the form when it loses focus (unless it loses focus to another item in the subsection manager, which I think would be a deliberate action).  Alternatively, close the form but keep the changes cached somewhere, and load the dirty form when the item is next opened.

**Comment by nilshoerrmann** [comment]
The next release will solve this problem by no longer closing the editor automatically.
