### ISSUE TITLE
Show only related items

### ISSUE THREAD

**Issue by markgoodyear** [symphonists/subsectionmanager#64]
A feature request would be to only show the related items for the section, rather than showing items across all sections.

This is in response to:
"As the SSM is able to filter by tags a solution would be as easy as adding a pseudo “self” tag to the fields settings." posted on http://symphony-cms.com/discuss/thread/25496/1/#position-18

**Comment by nilshoerrmann** [comment]
This can be achieved by disabling subsection search in the field settings.
