### ISSUE TITLE
PHP error causing blank pages when SSM is included in a Symphony datasource in 2.2 beta 3

### ISSUE THREAD

**Issue by doug-stewart** [symphonists/subsectionmanager#68]
I noticed this in beta 2 as well, by the way.

Basically, if you include the SSM field in your datasource and then include that datasource on a page, that page will show up blank. This includes if you try to debug it. There's no error in Symphony's logs but if I check my PHP logs I find the following error:

```
[19-Jan-2011 15:36:50] PHP Fatal error:  Cannot access protected property FieldManager::$_Parent in [root]/extensions/subsectionmanager/fields/field.subsectionmanager.php on line 612
```

This error is repeated every time I refresh the page. The line corresponds to this function:

```
$order = $this->_Parent->_Parent->Database->fetchVar('order', 0,
    "SELECT `order`
    FROM `tbl_fields_subsectionmanager_sorting`
    WHERE `entry_id` = " . $wrapper->getAttribute('id') . "
    AND `field_id` = " . $this->get('id') . "
    LIMIT 1"
);
```

For experimentation's sake, I tried changing `tbl_fields_subsectionmanager_sorting` to `sym_fields_subsectionmanager_sorting` since that's the actual entry in my database, according to PHPMyAdmin, but it didn't change the error.

**Comment by nilshoerrmann** [comment]
This should be fixed in the `experimental` branch.
