### ISSUE TITLE
bug: Doesn't work in IE7

### ISSUE THREAD

**Issue by kanduvisla** [symphonists/subsectionmanager#69]
In some cases, the subsection manager gets totally screwy in Internet Explorer 7. (or IE8 compatibility mode). Screenshot:

<img src="http://www.gielberkers.com/ssmie7.png" />

I don't know what exactly goes wrong, but it also pops this error message:
{{{
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)
Timestamp: Sun, 23 Jan 2011 10:45:18 UTC

Message: 'this.textContent' is null or not an object
Line: 358
Char: 8
Code: 0
URI: http://localhost/extensions/subsectionmanager/lib/stage/symphony.stage.js?v=1.0.1
}}}

**Comment by nilshoerrmann** [comment]
This should be fixed in the latest Subsection Manager beta. Can you confirm this?

**Comment by nilshoerrmann** [comment]
I just checked and it's working for me in IE 7 + 8 using SSM 1.1beta.
