### ISSUE TITLE
Can't delete an item if it is used in another subsection manager field

### ISSUE THREAD

**Issue by michael-e** [symphonists/subsectionmanager#7]
This bug won't be very important in daily usage, I think.

If you have more than one subsection field, each of them referencing the same (sub-)section, you won't be able to delete an item. Upon page reload, you will notice that the item is still there.

**Comment by nilshoerrmann** [comment]
Are we talking about _deleting_ (as in delete all related database information) or about _removing_ (as in remove selection)?

**Comment by michael-e** [comment]
Deleting.

**Comment by nilshoerrmann** [comment]
I'm not sure how this could be solved. Closed for now

**Comment by michael-e** [comment]
Never mind. As I described, this only occurs in idiotic constellations...
