### ISSUE TITLE
bug: Search Index not built in IE

### ISSUE THREAD

**Issue by kanduvisla** [symphonists/subsectionmanager#70]
The search Index is not built in IE. (tested in IE8), that's why IE gives the following error:

{{{

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)
Timestamp: Sun, 23 Jan 2011 10:45:18 UTC

Message: 'this.textContent' is null or not an object
Line: 358
Char: 8
Code: 0
URI: http://localhost/extensions/subsectionmanager/lib/stage/symphony.stage.js?v=1.0.1
}}}

**Comment by nilshoerrmann** [comment]
This should be fixed in the latest Subsection Manager beta. Can you confirm this?

**Comment by nilshoerrmann** [comment]
I just checked and it's working for me in IE 7 + 8 using SSM 1.1beta.
