### ISSUE TITLE
Weird behavior with Subsection Manager 1.0.1 and Symphony 2.1.2

### ISSUE THREAD

**Issue by bzerangue** [symphonists/subsectionmanager#75]
Nils, 

I ran across a peculiar bug with Subsection Manager 1.0.1 and Symphony 2.1.2. This is an existing site that was upgraded fully from Symphony 2.06 to Symphony 2.1.2. Mediathek or Subsection Manager was NOT installed on this site before. I installed 1.0.1 (since 1.1 is not compatible with Symphony 2.1.2). 

After the install, I added the subsection manager field to a section called People. The Subsection Manager field was pulling from the Images section and then I ran across the following error. When you go to the field, click on it, the drawer opens up with a duplicate field. 

I recorded a quick screencast to show what it's doing. 

http://screenr.com/1Nv

**Comment by bzerangue** [comment]
FYI... ALSO, the CREATE NEW button doesn't work, doesn't respond to a click.

**Comment by nilshoerrmann** [comment]
Brian, what are your SSM settings?

I remember that I fixed this issue after the release of version 1.0 but there were a lot of Symphony 2.2 related changes afterward. Could you please checkout the new tag `1.0.2` that I just created and see if that helps. Thanks!

SSM 1.1 contains a lot of fixes and improvements. Is there a chance that you are able to update your install to Symphony 2.2 when it's released?

**Comment by nilshoerrmann** [comment]
By the way: Are there any errors in your JavaScript console or is it possible that the JavaScript needed for SSM is attached to the backend twice?

**Comment by bzerangue** [comment]
Nils, I think I found the culprit. Fazal's old Mulitselect to Checkboxes extension was the culprit. When I uninstalled that, it worked fine. It looks as if the Javascript from Multiselect was conflicting.

**Comment by nilshoerrmann** [comment]
Ah, wonderful (well, wonderful that it's not related to SSM). Have a look at Simone's Better Forms extension which is looking really nice and handles checkboxes and multiselects nicely.

**Comment by bzerangue** [comment]
I will. I tried that one out, but it conflicts with Nick's Publish Filtering extension right now. I use the publish filtering extension all the time. I told Simone about the conflict.  It is a great extension though.
