### ISSUE TITLE
subsectionmanager.settings.css

### ISSUE THREAD

**Issue by tmslnz** [symphonists/subsectionmanager#76]
In line 82 of `extension.driver.php` there is a call to append the `subsectionmanager.settings.css` to the head of Symphony admin, but there is no .css file in the specified path.

**Comment by nilshoerrmann** [comment]
Thanks for the report. This file is no longer needed and should no longer be added to the backend. I'll post a fix soon.

**Comment by nilshoerrmann** [comment]
See SSM 1.1.1.
