### ISSUE TITLE
White page when enabled extension...

### ISSUE THREAD

**Issue by toledox82** [symphonists/subsectionmanager#78]
Hi Nils, bug on enable extension... white page.

I recorded the steps on a clean install...
http://screenr.com/FEv

**Comment by nilshoerrmann** [comment]
SSM 1.1.x is compatible with Symphony 2.2 only. Please use version 1.0.1 on Symphony 2.1.x.

**Comment by toledox82** [comment]
Sorry Nils, I was sure I was using the latest version of Symphony =/

**Comment by nilshoerrmann** [comment]
Well you are: Symphony 2.2 is expected to be released these days. A release candidate has been posted on the forum.
