### ISSUE TITLE
Datasource's html-encode setting not effecting subsections

### ISSUE THREAD

**Issue by helion** [symphonists/subsectionmanager#79]
Symphony v2.1.2 and SubsectionManager v1.0.1 

I'm using subsection manager to attach blocks of raw html to parent sections. In the data source I've added the sub-section to the 'Included Elements' selection and 'html-encode Text' is checked.

When that data source is passed to a page the html for the parent sections' text areas is properly encoded but the html from the subsections isn't.

**Comment by helion** [comment]
I just saw that Symphony v2.2 has been released. I'll upgrade it and SubsectionManager and test again.

**Comment by helion** [comment]
Upgraded to Symphony v2.2 and SubsectionManager v1.1.1 and HTML from subsections isn't being encoded.

**Comment by nilshoerrmann** [comment]
Hm, I'm not sure if this is an issue of this extension or of the core. I'll have to check that.

**Comment by nilshoerrmann** [comment]
This will be fixed in the next release of Subsection Manager.

**Comment by kirkstrobeck** [comment]
Hmm this is still a problem..
