### ISSUE TITLE
Newly created items don't appear in the item list

### ISSUE THREAD

**Issue by michael-e** [symphonists/subsectionmanager#8]
Newly created items are expected to appear in the list of available items. But they only do so after saving the whole entry.

**Comment by michael-e** [comment]
Initially (i.e. before saving) a new item even appears in the list of _selected_ (=linked) items. It should remain there after being saved. (New items will be created to be linked to the main entry.)

**Comment by nilshoerrmann** [comment]
This bug seems to be related to the latest changes in `class.subsectionmanager.php` (which introduced template selection).

**Comment by nilshoerrmann** [comment]
Additionally, newly created item do not clear queue message (`There are currently no items available. Perhaps you want create one first?`).

**Comment by nilshoerrmann** [comment]
This should be fixed [here](http://github.com/nilshoerrmann/subsectionmanager/commit/b500f7cd2f067f87cf99a242e74c228e00e9911e) and [over there](http://github.com/nilshoerrmann/stage/commit/ef68ced70174f15be221b8371e354f054c650283).

**Comment by michael-e** [comment]
Hmmm, doesn't work for me (Safari and Firefox on OS X).

**Comment by nilshoerrmann** [comment]
Have you cleared your cache?

**Comment by nilshoerrmann** [comment]
And have you updated all three components (Stage, Subsection Manager, Draggable)?

**Comment by michael-e** [comment]
Yes and yes. Additionally, once again I can't create new items after having deleted one. (Wasn't this solved?)

**Comment by nilshoerrmann** [comment]
Hm - it's all working for me.

**Comment by michael-e** [comment]
Strange. Maybe an issue with the Git ZIP download? I will pull the repo(s) and try again.

**Comment by nilshoerrmann** [comment]
Sent you an email with a copy of the version I'm currently using - maybe something is messed up in one of the repositories.

**Comment by michael-e** [comment]
I tried the pulled repository as well as the version you sent me, both on Symphony 2.0.8 RC1 and 2.0.7. No luck.

**Comment by nilshoerrmann** [comment]
This is most likely related to these issues: http://github.com/nilshoerrmann/subsectionmanager/issues#issue/31 and http://github.com/nilshoerrmann/subsectionmanager/issues#issue/30
