### ISSUE TITLE
Drag and drop creating multiple entries

### ISSUE THREAD

**Issue by helion** [symphonists/subsectionmanager#80]
Symphony 2.2 and SubsectionManager 1.1.1 upgraded from 2.1.2 and 1.0.1

Drag-able subsections are creating 3 copies of the drop text in my text area field. 

I've tested this using a subsection with text input labeled 'Alt-Text' and file upload field labeled 'Image' and with both with default and custom drop text and with/without markdown formatting. I've also tried just using a subsection with a single text input field on different entries and removing the original subsection field and creating a new one.

**Comment by nilshoerrmann** [comment]
I cannot reproduce this. A few questions:
- Have you checked that your captions are set properly?
- Are there any errors in your JavaScript console?
- Are there any other extensions that might conflict with SSM?

**Comment by klaftertief** [comment]
Some more questions:
- Are there any special characters like quotes in the (custom) drop text?
- What browser are you using?
- Are the three copies identical or do they differ?

**Comment by helion** [comment]
Sorry to take so long getting back. 

I'm using Firefox 3.6.14 and Firebug console shows no errors. I get the same behavior in up to date versions of Safari and Chrome.

In addition to the extensions that came packaged with Symphony installed I have CodeMirror and PublishNotes but this problem existed before I installed them. I've also disabled all of the extensions that I can with no improvement.

All three copies of the drop text are identical.

Defaults if I don't create custom settings : 
Caption - {$alt-text}&lt;br /&gt; &lt;em&gt;{$image}&lt;/em&gt; 
Drop Text - &lt;img src="http://localhost/test-newsite/workspace/images/planing_350px.jpg" alt="working with a planer.  /images/planing_350px.jpg" /&gt;

I've also tested with only {$alt-text} and {$image} in caption and drop text respectively and with only plain text (test and testing) with the same result.

I am running on XAMPP on Windows 7. When I get the time I will try replicating the problem in a fresh install of symphony in the same environment and on my hosted server.

**Comment by helion** [comment]
Ok, I've done a fresh install on my localhost of Symphony 2.2 with the default workspace and SubsectionManger 1.1.1 and drag and drop is now working fine. I'll try and find a way to replicate the problem and will let you know the results.

**Comment by helion** [comment]
Success! .... of a sort anyway. 

I'm getting three copies of the drop text because I have three different subsection fields attached to the section. One for the image, and two that let me place chunks of html at different locations on the final page.

**Comment by 4ll4n** [comment]
I'm also getting this issue. I have 2 subsection fields attached to 1 section to pull images and documents. When item is dropped, I get 2 instances of ![image alt](/imagepath/image.png)

**Comment by helion** [comment]
I imagine that part of the javascript responsible for drag and drop works off of a class reference shared by every instance of a SubsectionManager field.  I've only given the javascript in the extension a quick skim so far but hope to take a more thorough look soon.

**Comment by BBQbrains** [comment]
I also have a section with 3 instances of SSM, and I get 3 copies of the same image for each drop. This happens in IE8, FF 4.0, and Chrome 10.0.648.151.

**Comment by ahwayakchih** [comment]
Same thing happens on Chrome 12.0.729.0 (6 fields = 6 copies of dropped text).

**Comment by nilshoerrmann** [comment]
This should fix it: https://github.com/nilshoerrmann/subsectionmanager/commit/4845a299cca12dacb5ae7fa3ac6ce944e8a1dded

**Comment by ahwayakchih** [comment]
Those two changes fixed problem for me. Thank you.

**Comment by helion** [comment]
Looks to be working for me as well. Thanks so much.

**Comment by ahwayakchih** [comment]
I just got a lot of errors on entry in section where there are no textareas. After changing code from:

```
        if(!('drop' in textarea.data('events'))) {
```

to:

```
        var events = textarea.data('events');
        if(!events || events.length < 1 || !('drop' in events)) {
```

it works ok.
