### ISSUE TITLE
Swf file can not be output

### ISSUE THREAD

**Issue by kamwing** [symphonists/subsectionmanager#81]
Swf file can not be output in Data Sources

**Comment by nilshoerrmann** [comment]
Could you be a bit more descriptive, please?
- What is going wrong?
- How did you expect it to work?
- Which fields are involved?
- What's your SSM setup?

Thanks!

**Comment by kamwing** [comment]
1 Create  a "images" section with 1 "unique file upload" field.
2 Then include this "images" section to a "cases section".
3 Go to content > cases > create new > upload a images  and a swf file.
4 Create new "cases" datasources and include "cases" section.
5 Create new "cases" page include "cases" datasources.
6 upload a image and a swf item in SSM then save.
7 use cases/?debug view the output xml  only image item was output

( Sorry for my bad english, Do you see what I mean? )

**Comment by nilshoerrmann** [comment]
Thanks, kamwing.

I'm not sure if this is a SSM issue or a problem with the Unique File Upload field. Does Symphony output the SWF file in the XML when you create a data source that fetches from your subsection directly (not using SSM)?

**Comment by kamwing** [comment]
Yes, Symphony output the SWF file in the XML (not using SSM)

**Comment by nilshoerrmann** [comment]
That's really strange as SSM just uses the XML returned by the Unique File Upload field.

I'll have a look at it.

**Comment by kamwing** [comment]
Thanks, nilshoerrmann.

**Comment by nilshoerrmann** [comment]
Is anyone around able to reproduce this issue?

**Comment by kamwing** [comment]
Now I using Symphony 2.2.1 Beta 2 and this issue has been resolved

**Comment by nilshoerrmann** [comment]
Thanks for the feedback.
