### ISSUE TITLE
SSM and Datetime don't play nice

### ISSUE THREAD

**Issue by brendo** [symphonists/subsectionmanager#84]
As the title suggests. Both extensions include the Stage module which causes the interface to get a doubled appearance. I believe this is because the SSM appends the `?v=1.1.1` to the script which breaks the duplicate checking.

**Comment by nilshoerrmann** [comment]
This has been fixed in the `tabs` branch. The next releases of Date and Time and Subsection Manager will make sure that there are no Stage related conflicts.
