### ISSUE TITLE
Multiple Subsections

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/subsectionmanager#87]
It should be possible to link multiple subsections.

**Comment by klaftertief** [comment]
Do you already have ideas for the interface to support multiple subsections? I'm asking because I just started again with a _staged_ version of the Upload Selectbox field that supports sub-directories. At the moment I'm just showing a select box above the search input.

**Comment by nilshoerrmann** [comment]
No, I don't have a concept for an interface yet but I see a need to it in the future. This issue was more or less a reminder for me.

**Comment by nilshoerrmann** [comment]
This seems to be a nice idea that is way to complicated for now. Closing this issue.
