### ISSUE TITLE
Eternal spinning wheel if no search results are found

### ISSUE THREAD

**Issue by michael-e** [symphonists/subsectionmanager#9]
If search does not return any items, there will be a slow-moving "spinning wheel". This normally indicates that the engine is working hard (which is worth the wait). In fact waiting won't help. So it would be better to simply display nothing or - alternatively - a text like "nothing found".

**Comment by nilshoerrmann** [comment]
Do we talk about searching (typing in a search term) or browsing (clicking into the input field)? Which browser are you using?

**Comment by michael-e** [comment]
Searching, latest Safari and Firefox on Mac OS X. When the last item has vanished from the list (because it does not match your search), there is the spinning wheel.  It's an elegant one, but misleading. :-)

**Comment by nilshoerrmann** [comment]
;)

I'll have a look a it.

**Comment by nilshoerrmann** [comment]
This is a Stage issue that has been fixed here: http://github.com/nilshoerrmann/stage/commit/d69131d84f6b1e925bda107eeb326a7965313d0f
