### ISSUE TITLE
Datasource generation problem [database update bug]

### ISSUE THREAD

**Issue by pngised** [symphonists/subsectionmanager#90]
I have the same problem as Brendan [here](http://symphony-cms.com/discuss/thread/50421/9/#position-171)

I have a section with a Subsection Manager for uploading images. Only the first two images are returned in the datasource.  
After I reorder just one of them they are updated into database (and returned in datasource).

This is a strange behaviour...

**Comment by pngised** [comment]
I find the problem in **stage.publish.js**

you update the sort-order value only when sorting  
// Save sortorder  
field.find('input[name*="sort_order"]').val(sortorder);

This never happen when create a new item...

**Comment by nilshoerrmann** [comment]
This will be solved together with issue #86.

**Comment by pngised** [comment]
I'll test it, thank you.
