### ISSUE TITLE
Missing option "prevent editing of items"

### ISSUE THREAD

**Issue by michael-e** [symphonists/subsectionmanager#91]
It would be rather cool to have an option "prevent editing of items". Even very rather cool!

**Comment by nilshoerrmann** [comment]
> Even very rather cool!

Bavarian superlative?

**Comment by michael-e** [comment]
Yes, here in Bavaria we have not seen no better superlative. :-)

**Comment by nilshoerrmann** [comment]
Hey, and you know the double negative :)

**Comment by michael-e** [comment]
Yeah, that's rather cool, isn't it? Even very rather cool!

**Comment by nilshoerrmann** [comment]
Du weißt ja, wir Norddeutschen sind eher etwas unterkühlt - wir haben es nicht so mit Superlativen ...

**Comment by michael-e** [comment]
Ja, ich hab' noch keinen Norddeutschen nicht getroffen, der so heißblütig war wie ich.

LOL.

**Comment by nilshoerrmann** [comment]
Ich auch nicht.

**Comment by nilshoerrmann** [comment]
Is this an important feature for you, Michael, or is it just a nice have?
