### ISSUE TITLE
Can click on messages which produces errors

### ISSUE THREAD

**Issue by brendo** [symphonists/subsectionmanager#93]
When you first use the Subsection Manager on a blank install if there any no entries the following text is displayed. "There are currently no items available. Perhaps you want create one first?"

This line of text however is clickable, and can be added to the stage. When attempting to click on it, this will load an 'entry not found' error in the iframe.

**Comment by nilshoerrmann** [comment]
This has been popping up a thousand times. I'm not sure what I'm doing wrong that I always reintroduce this bug after just having fixed it ...

**Comment by nilshoerrmann** [comment]
This is a Stage issue which has been fixed.
