### ISSUE TITLE
Duplicate_entry creates too many items in subsection field

### ISSUE THREAD

**Issue by ahwayakchih** [symphonists/subsectionmanager#94]
Using [duplicate_entry](https://github.com/nickdunn/duplicate_entry) extension to "Save as new" subsection entry, makes Subsection Manager create new item in list, but also change old item name into new one (if title/caption changed).

**Comment by nilshoerrmann** [comment]
Could you please verify that this issue is related to Subsection Manager or if it can be solved in Duplicate Entry. Thanks!

**Comment by ahwayakchih** [comment]
duplicate_entry JavaScript is a lot smaller, so i started there.

It looks like it simply adds "Save as new" button, which, when clicked, changes target of form.action from edit to new before form is submitted.

Can it be that Subsection manager caches ID and/or action (new or edit) somewhere and does not check where form was actually submitted (or where iframe was reloaded from)?

**Comment by nilshoerrmann** [comment]
Now I'm curious: are we talking about using this inside the inline editor of subsection items?

Otherwise there is nothing special that Subsection Manager does that I can think of could cause this issue.

**Comment by ahwayakchih** [comment]
> are we talking about using this inside the inline editor of subsection items?

Yes. Sorry i was not specific enough. Bug shows up when i start editing entry in "inline editor" (i mean: while editing entry in section A, which has Subsection Manager field pointing to section B, i click on one of items/entries in that field, to start editing that "section B" entry).

**Comment by nilshoerrmann** [comment]
Okay. This cannot work in the current setup I'm afraid. It would be possible to extend Duplicate Entry though to allow subitem duplication as well. 

Sorry to say, but I've no plans to integrate such a feature in one of Subsection Manager's next releases. Closing this issue for the moment.

**Comment by ahwayakchih** [comment]
Additional explanation: bug does not make Subsection Manager actually create bogus entries, or change values of wrong entries. It is only visual presentation of Subsection field, that is showing wrong information, as far as i know.

**Comment by ahwayakchih** [comment]
Can't You simply make Subsection Manager to check where new (reloaded) data comes from? Or does Subsection Manager make many assuptions before user clicks to edit or create new item?

**Comment by nilshoerrmann** [comment]
Of course, _I could_. But it's not on the list at the moment as I need to keep the features of this extension manageable. It's possible to hook into the interface using a second extension so this is the way to go at the moment. It would be best to implement the needed steps into Duplicate Entry in my opinion as entry duplication is not a Symphony core feature.

**Comment by ahwayakchih** [comment]
I'm not asking about adding new feature, or special handling for selected other extensions (i agree that such things should be avoided, at least in main part of extension).
But many things can happen between showing entry edit form and getting new entry form after form was submitted. I think that ID can change for various reasons.
Subsection Manager is one of the best extensions for Symphony, and i certainly do not want to change that (unless it is a change to "even better" :).

So...

I tried few things and it looks like Subsection Manager does know about new entry ID. It just did not check if `data-value` is different than `id`.
One has to change only one line, and only by a tiny bit, to make it work. Line https://github.com/nilshoerrmann/subsectionmanager/blob/master/assets/subsectionmanager.publish.js#L342 looks like this:

```
var queue_item = queue.find('li[data-value="' + item.attr('data-value') + '"]');
```

after changing it to:

```
var queue_item = queue.find('li[data-value="' + id + '"]');
```

everything works perfect :D. Is such change OK?

**Comment by nilshoerrmann** [comment]
Thanks Marcin. I'll have a look at it. Reopening this thread.

**Comment by ahwayakchih** [comment]
Thank You for reconsidering :).

**Comment by nilshoerrmann** [comment]
I just installed Duplicate Entry and tried your code and I'm not sure if this creates a logical behaviour: If you clicked on `Save as new`, I'd expect the generation of a new selected subsection item while keeping the old one in the list. Which is not what's happening.

Is this a misunderstanding on my side?

**Comment by ahwayakchih** [comment]
Hmm... You're right.

It depends on the workflow. I used it to quickly create new subsection entry based on some other, similar one, without a need to keep that other one linked/selected-in-list. I guess that both ways could be useful, and Your way of thiking might be more intuitive for end-user.

Still, i think that version with fix applied works better than without it, because it does not change original entry in item list (it adds new item and selects it instead of original one).

I guess that, since Subsection Manager knows both old and new IDs, it could use fix like i mentioned above, plus select additional item (old ID) if it is still available, i.e., if it was not deleted by the same process that created new entry.
Of course that would require some additional code. Should i try to implement it?

**Comment by nilshoerrmann** [comment]
In your case wouldn't it be easier to just open the entries in the related Symphony section? If they don't need to be attached to the Subsection Manager field as selected items.

> Still, i think that version with fix applied works better than without it, because it does not change original entry in item list

I don't think so as using an differing id provided by the drawer's iframe runs the risk to break the synchronisation between the selection, the queue and the storage. Actually thinking of a vanilla Symphony install + Subsection Manager setup, it should not be possible that a new id is provided.

This is why I said above that I think it would be best to enhance Duplicate Entry to handle Subsection Manager fields as well. I mean to say: providing the functionality you are describing on top of Subsection Manager.

Just so you know: I think it's a helpful feature you are requesting. I'm just not convinced that Subsection Manager should handle this.

**Comment by ahwayakchih** [comment]
> In your case wouldn't it be easier to just open the entries in the related Symphony section?

In this case, not really. Subsection Manager points to "Photos" section. Each photo can be "attached" (thanks to Subsection Manager) to different articles. Each photo can have short description, but description can be different for different articles.

Of course i could add Subsection Manager field in Photos section, so each photo can have multiple descriptions, but that would clutter interface and make things a bit less readable for authors.

Another Subsection Manager field points to section which keeps specifications data. Specifications section has a lot of fields, but i wanted it to be possible for author to create/edit specifications while writing article, without a need to jump to different pages. So, specifications will also use "Save as new" feature quite often (different models can have similar specifications, so it will be easier to create new by copying old and editing it than entering all data again).

I'm using Subsection Manager field because it makes process of creating article a lot smoother. If author will have to jump to other sections all the time anyway, than Subsection Manager's main advantage will disappear :(.

Also i think that checking ID is still useful just to be on the safe side, even tough change of ID number seems unlikely in "vanilla Symphony + Subsection Manager" setup.

Additional code could be added later to Duplicate Entry, so it would call Subsection Manager to select new item next to old one, instead of deselecting old and selecting new one.

**Comment by nilshoerrmann** [comment]
> I'm using Subsection Manager field because it makes process of creating article a lot smoother. If author will have to jump to other sections all the time anyway, than Subsection Manager's main advantage will disappear :(.

Yeah, I know. But give it time to grow, please :)
This extension is a beast because of the various numbers of use cases. It needs to evolve step by step and over time. Otherwise I'll get crazy!

> Also i think that checking ID is still useful just to be on the safe side, even tough change of ID number seems unlikely in "vanilla Symphony + Subsection Manager" setup.

Maybe, yes. But if a mismatch is detected SSM would have to default to something and this is the stored id again.

**Comment by ahwayakchih** [comment]
>  It needs to evolve step by step and over time. Otherwise I'll get crazy!

:).

> But if a mismatch is detected SSM would have to default to something and this is the stored id again.

Why not new ID? New one is "the most up-to-date". Subsection Manager does not know if old ID still exists, but it can be sure that new one does exist (at least it did at the moment of receiving data from server).

**Comment by nilshoerrmann** [comment]
Because a new id means that something went wrong. Again looking at a vanilla install.

This is a problem that needs to be handled in the future but in order to do so the internal storage of Subsection Manager needs to be simplified: if SSM retrieves a new id (why ever) what should happen in the queue and the storage select box? How should these things be kept in sync correctly?

These are questions that have no easy answer.

**Comment by ahwayakchih** [comment]
>  if SSM retrieves a new id (why ever) what should happen in the queue and the storage select box?

I think it should update it's data with new information. Maybe remove item with old ID from the cached list (that would break things again for my case, but it would make SSM handling of data a bit safer) or update information about it by doing another call to server?

**Comment by nilshoerrmann** [comment]
For your information: 
- [Discontinuing Support for Subsection Manager](http://getsymphony.com/discuss/thread/83270/7/#position-121)
- [Investigating Relationships](http://getsymphony.com/discuss/thread/96191/)
