### ISSUE TITLE
Drag and drop textarea overlay visible only for first Subsection Manager field.

### ISSUE THREAD

**Issue by ahwayakchih** [symphonists/subsectionmanager#97]
Textarea overlay shows up only when dragging and dropping item from first of the Subsection Manager fields in section.
Dragging and dropping from any other Subsection Manager field happens without textarea overlay.

**Comment by nilshoerrmann** [comment]
This should do the trick: https://github.com/nilshoerrmann/stage/commit/8a581cc9bfe5a57e88e16767d5a628a1222bd3a7

**Comment by ahwayakchih** [comment]
It did, thank you :).
