### ISSUE TITLE
Test 1.2

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/subsectionmanager#99]
Checkout https://github.com/nilshoerrmann/subsectionmanager/tree/1.2beta

**Comment by nilshoerrmann** [comment]
Next one: https://github.com/nilshoerrmann/subsectionmanager/tree/1.2RC1

**Comment by vlad-ghita** [comment]
I just tested 1.2RC1. Check out [this](http://symphony-cms.com/discuss/thread/50421/13/#position-258) post on the forum.

**Comment by nilshoerrmann** [comment]
Release Candidate 2: https://github.com/nilshoerrmann/subsectionmanager/tree/1.2RC2
